### ISSUE TITLE
How to input a value

### ISSUE THREAD

**Issue by hiuxia** [rcarriga/nvim-dap-ui#101]
Thanks for this awesome plugin! I use this to debug python and everything works well except input. When I set a breakpoint at the 'input()' position, the repl report the eof error. 
So I want to know how to input a value by using this plugin(My English is poor, please pardon me for that)?

**Comment by rcarriga** [comment]
Glad you're enjoying it :smile: Can you provide a code example of your issue?

**Comment by hiuxia** [comment]
Thank you for your instant reply! Not something so sophisticated.I have just tested something like `test = input()`, and only by setting the `console = integratedTerminal` could I get the code continue. 
By the way, after reading the doc of nvim-dap and nvim-dapui, I  think maybe the bottom tray can't get input? The following is the **_eof error_** example.
![image](https://user-images.githubusercontent.com/98009342/168257179-4b2cebb9-4af3-4a98-bd78-698dd04d0320.png)
Besides, setting the IntegratedTerminal is really hard to use, for appearance and moving between windows!

**Comment by hiuxia** [comment]
Sorry, I shouldn't ask this question here.

**Comment by LennyPhoenix** [comment]
I'm actually also getting this problem with python.
Minimal repro program:

```python
user_input = input("Echo: ")
print(user_input)
```
