### ISSUE TITLE
attempt to get length of local 'prev_line ' (a nil value)

### ISSUE THREAD

**Issue by fgheng** [rcarriga/nvim-dap-ui#102]
Hello, I am tring to debug python code, but while I used repl, something error occured, look at this pic and gif.
![image](https://user-images.githubusercontent.com/50551377/169698529-02186dd9-8eb3-4157-a17e-c5beb8a72d0b.png)

gif:
![Peek 2022-05-22 21-54](https://user-images.githubusercontent.com/50551377/169698677-feee70f8-28e4-45cb-9136-49dcea26605f.gif)

**Comment by JoseConseco** [comment]
I have this too. Maybe because I'm on 8.0 dev build?  Any way to fix @fgheng

**Comment by rcarriga** [comment]
Yep NeoVim's LSP doesn't handle prompt buffers well unfortunately so you can't have an LSP client attached to the REPL. This is an issue for the NeoVim repo

**Comment by askfiy** [comment]
Is it possible to catch this unusual behavior with pcall as a temporary solution?
