### ISSUE TITLE
Add jump to eval() window param

### ISSUE THREAD

**Issue by JoseConseco** [rcarriga/nvim-dap-ui#103]
from docs i we use:
```vnoremap <M-k> <Cmd>lua require("dapui").eval()<CR>```
2x then we will jump to opened  eval() window.  It would be cool if  eval(true) would auto jump to opened window. 
Not big deal, but this looks ugly: 
```:lua require('dapui').eval()<CR><Cmd>lua require('dapui').eval()<CR>```

**Comment by rcarriga** [comment]
There is already the `enter` param in the second argument table. See `:h dapui.eval()`

**Comment by JoseConseco** [comment]
Thank this works. My bad for not checking docs.
