### ISSUE TITLE
Console filetype is ''

### ISSUE THREAD

**Issue by Zane-** [rcarriga/nvim-dap-ui#106]
I see that the filetype of the console is supposed to be 'dapui_console', but it seems like it's just an empty string instead.

`:echo &ft` just displays nothing, and adding `''` to the disabled filetypes for lualine and nvim-cmp result in the expected behavior.

**Comment by rcarriga** [comment]
Thanks for the report :smile: Fixed in latest commit

**Comment by Zane-** [comment]
Thanks for the quick fix, works fine now
