### ISSUE TITLE
Typing in dap-repl triggers lsp error

### ISSUE THREAD

**Issue by shawnyu5** [rcarriga/nvim-dap-ui#109]
Using built-in nvim lsp, when typing in the dap repel, I get the following error.

![image](https://user-images.githubusercontent.com/55592708/173723859-2becf929-484e-41f9-9a32-287994b2276a.png)

Not sure if this is a dap ui / dap, or builtin lsp issue.

Runing the latest neovim version:

```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by shawnyu5** [comment]
Ah, setting a autocommand to stop lsp in dap repls solves the issue.

**Comment by rcarriga** [comment]
Same as #102, this is a NeoVim issue. Workaround is to disable LSP for the REPL buffer
