### ISSUE TITLE
Empty console

### ISSUE THREAD

**Issue by EpsilonKu** [rcarriga/nvim-dap-ui#110]
![gscreenshot_2022-06-15-122633](https://user-images.githubusercontent.com/63652620/173898998-ee3f96a8-4e5a-4182-9ab3-3fda792013ff.png)
It seems like integrated terminal created on new window (not on bottom).
```
		tray = {
			elements = {
				"console"
			},
			size = 10,
			position = "bottom" -- Can be "bottom" or "top"
		},

```

**Comment by rcarriga** [comment]
Can you reproduce with this init.lua
```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand("~/.config/nvim"))
vim.opt.packpath:remove(vim.fn.expand("~/.local/share/nvim/site"))

-- append test directory
local test_dir = "/tmp/nvim-config"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
  vim.cmd("packadd packer.nvim")
  install_plugins = true
end

local packer = require("packer")

packer.init({
  package_root = test_dir .. "/pack",
  compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
  -- Packer can manage itself
  use("wbthomason/packer.nvim")

  use({
    "rcarriga/nvim-dap-ui",
    requires = {
      "mfussenegger/nvim-dap",
    },
    config = function()
      require("dapui").setup()
    end,
  })

  if install_plugins then
    packer.sync()
  end
end)
```
Run with `nvim --clean -u init.lua` and then run `:lua require("dapui").toggle()`

**Comment by EpsilonKu** [comment]
Ok, it works perfect on Java and it won't work with Flutter. I guess because [flutter-tools](https://github.com/akinsho/flutter-tools.nvim) use some custom debug method.

**Comment by rcarriga** [comment]
It looks like somewhere the `terminal_win_cmd` option is set for nvim-dap which is also used by nvim-dap-ui. Do you set that somewhere?

**Comment by EpsilonKu** [comment]
No, I didn't use `terminal_win_cmd`. It seems like flutter-tools [simulate](https://github.com/akinsho/flutter-tools.nvim/blob/04d6d1ed7f11d9bf8be6e854544389d373ed2734/lua/flutter-tools/runners/debugger_runner.lua#L53-L83) debugging with nvim-dap.

**Comment by rcarriga** [comment]
Ah OK so that's not the actual dap console but a window created by flutter tools?

**Comment by EpsilonKu** [comment]
> Ah OK so that's not the actual dap console but a window created by flutter tools?

Yeah, even if I use `terminal_win_cmd`. It ignores it. So I guess better to open on flutter-tools and close it.Yea?

**Comment by rcarriga** [comment]
Yep I think so :+1:
