### ISSUE TITLE
Configurable message prompts

### ISSUE THREAD

**Issue by askfiy** [rcarriga/nvim-dap-ui#112]
![图片](https://user-images.githubusercontent.com/81478335/174573266-882d7ca6-8e70-4c3a-830c-446c45c3bf32.png)

I noticed that now whether I start debugging or continue debugging, it pops up the annoying `notify` popup.

Maybe we can use `vim.api.nvim_echo` to display these debug content, some important notifications can use `notify`.

It should be user configurable:

Similar to:

```
require("dap").setup({
    informe_method = "notify | echo"
    ...
})
```

**Comment by rcarriga** [comment]
This is an issue for `nvim-dap`, which is sending the messages. I don't maintain `nvim-dap` :smile:

**Comment by askfiy** [comment]
Ok thank you, I should have raised it in `dap`.
