### ISSUE TITLE
Is Setup() supposed to cleanup layout?

### ISSUE THREAD

**Issue by ray-x** [rcarriga/nvim-dap-ui#115]
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/1681295/176596720-3fdd4234-427d-49c7-b084-a4ccd93f95dc.png">

From what I see, if 
1) call dapui.setup()
2) call daupui.open()
3) call dapui.setup() again without close the dapui windows
4) check layout is open with layout:is_open()

step 4 will return false even though the UI is not closed. From the logs, `opened_wins = {}` So I suspect setup() cleanup the opened_wins without destroy them.

There are no places mentioned setup() should be called only once.

Maybe before setup() cleanup everything, put some error messages if there are still opened windows.

**Comment by rcarriga** [comment]
It is not designed to be called twice but I've added a change to clear the layouts if it does happen.

**Comment by ray-x** [comment]
Thanks!
