### ISSUE TITLE
Bottom layout elements change sizes over time

### ISSUE THREAD

**Issue by CaptainKraft** [rcarriga/nvim-dap-ui#116]
When I start a debug session for the first time, the sizes are correct. After I close the session, reopen, and repeat, the far bottom-right (console in this case) element gets smaller and smaller. After closing neovim and reopening, it starts at the correct size again.

Here is my layout config:
```lua
  layouts = {
    {
      elements = {
        "stacks",
        { id = "scopes", size = 0.5 },
      },
      size = 30, -- 30 columns
      position = "left",
    },
    {
      elements = {
        { id = "console", size = 0.5 },
        "watches",
      },
      size = 0.25, -- 25% of total lines
      position = "bottom",
    },
  },
```

**Comment by rcarriga** [comment]
I'm not sure why it's happening but I'm guessing it's a rounding issue. I've put in a `reset` option for toggle/open so it'll always stay the same

**Comment by CaptainKraft** [comment]
That seems to have fixed it. Thanks
