### ISSUE TITLE
can't configure dapui using the setup function 

### ISSUE THREAD

**Issue by ruahman** [rcarriga/nvim-dap-ui#117]
I am trying to setup the following UI using the setup function.
![dapui-setup](https://user-images.githubusercontent.com/360398/177064632-9f0aed2d-9698-4f1c-b0af-09aae55bf800.png)

However this is what shows up when I toogle dapui.

![nvim-dapui](https://user-images.githubusercontent.com/360398/177064693-b2fd3c4c-707a-4918-a2e8-1c57e580babf.png)

what am I doing wrong????

**Comment by ruahman** [comment]
I just want scopes and watches on left and just the repo at the bottom.  what am I doing wrong?

**Comment by rcarriga** [comment]
I can't reproduce

Can you try with the following init.lua `nvim --clean -u minimal_init.lua`, let it install plugins and then run `DapUIToggle`
```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.stdpath("config"))
vim.opt.packpath:remove(vim.fn.stdpath("data") .. "/site")
vim.opt.termguicolors = true

-- append test directory
local test_dir = "/tmp/nvim-config"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
  vim.cmd("packadd packer.nvim")
  install_plugins = true
end

local packer = require("packer")

packer.init({
  package_root = test_dir .. "/pack",
  compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
  -- Packer can manage itself
  use("wbthomason/packer.nvim")

  use("mfussenegger/nvim-dap")
  use({
    "rcarriga/nvim-dap-ui",
    config = function()
      require("dapui").setup({
        layouts = {
          {
            elements = {
              "scopes",
              "watches",
            },
            size = 80,
            position = "left",
          },
          {
            elements = { "repl" },
            size = 0.25,
            position = "bottom",
          },
        },
      })
    end,
  })

  if install_plugins then
    packer.sync()
  end
end)

vim.cmd([[
command! DapUIToggle lua require("dapui").toggle()
]])
```

**Comment by ruahman** [comment]
Yup must be how I have my nvim setup.

![dapup](https://user-images.githubusercontent.com/360398/177181613-323699d4-3778-4abb-a997-bc411959f3d1.png)

here is where I am setting up packer.

` -- Install packer.nvim if not found.
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  packer_bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end

-- startup and add configuration plugins
return require('packer').startup(function(use)
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'

  use 'haishanh/night-owl.vim'

  use 'tpope/vim-commentary'
  use 'tpope/vim-surround'
  use 'romainl/vim-cool'
  use 'jiangmiao/auto-pairs'     

  use 'phaazon/hop.nvim'
  use 'unblevable/quick-scope'

  use 'kyazdani42/nvim-web-devicons'
  use 'kyazdani42/nvim-tree.lua'

  use 'hoob3rt/lualine.nvim'

  use 'L3MON4D3/LuaSnip'
  use "rafamadriz/friendly-snippets"

  use 'neovim/nvim-lspconfig'

  use 'hrsh7th/nvim-cmp'
  use 'hrsh7th/cmp-buffer'
  use 'hrsh7th/cmp-path'
  use 'hrsh7th/cmp-nvim-lua'
  use 'hrsh7th/cmp-nvim-lsp'
  use 'saadparwaiz1/cmp_luasnip'

  use 'nvim-treesitter/nvim-treesitter'
  use 'p00f/nvim-ts-rainbow'

  use 'kevinhwang91/rnvimr'

  use {
    'nvim-telescope/telescope.nvim',
    requires = {
      'nvim-lua/plenary.nvim', 
      'nvim-lua/popup.nvim', 
    }
  }
  use {'nvim-telescope/telescope-fzf-native.nvim', run = 'make' }

  use 'mfussenegger/nvim-dap'
  use 'rcarriga/nvim-dap-ui'
  use 'theHamsta/nvim-dap-virtual-text'
  use 'leoluz/nvim-dap-go'
  use 'mfussenegger/nvim-dap-python'
  -- use 'suketa/nvim-dap-ruby'

  require'plugins.hop'
  require'plugins.quick-scope'
  require'plugins.nvim-tree'
  require'plugins.lualine'
  require'plugins.luasnip'
  require'plugins.lsp'
  require'plugins.cmp'
  require'plugins.treesitter'
  require'plugins.ranger'
  require'plugins.telescope'
  require'plugins.dap'

  -- Automatically set up your configuration after cloning packer.nvim
  -- Put this at the end after all plugins
  if packer_bootstrap then
    require('packer').sync()
  end
end)
 `

---- this is where I am setting up DAP

local dap = require('dap')



-- lldb c/c++/rust
dap.adapters.lldb = {
  type = 'executable',
  command = '/usr/bin/lldb-vscode-10', -- adjust as needed, must be absolute path
  name = 'lldb'
}

dap.configurations.rust = {
  {
    name = 'Launch',
    type = 'lldb',
    request = 'launch',
    program = function()
      -- load the debug file that was created using ( cargo build )
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/target/debug/', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopOnEntry = false,
    args = {},
  },
}

dap.configurations.c = {
  {
    name = 'Launch',
    type = 'lldb',
    request = 'launch',
    program = function()
      -- load the debug file that was created using (clang -g )
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopOnEntry = false,
    args = {},
  },
}

require'dap-go'.setup()
require('dap-python').setup('/home/ruahman/.pyenv/shims/python')



require'nvim-dap-virtual-text'.setup()

require('dapui').setup({
  layouts = {
    {
      elements = {
        'scopes',
        'watches',
      },
      size = 40,
      position = 'left',
    },
    {
      elements = {
        'repl',
      },
      size = 10,
      position = 'bottom',
    },
  },
})




vim.keymap.set('n', '<leader>b', require'dap'.toggle_breakpoint)
vim.keymap.set('n', '<leader>c', require'dap'.continue)
vim.keymap.set('n', '<leader>s', require'dap'.step_into)
vim.keymap.set('n', '<leader>n', require'dap'.step_over)
vim.keymap.set('n', '<leader>u', require'dapui'.toggle)


Do you see any problems with how I'm configuring NVIM that could be causing this problem?

Thank you for your quick response.

**Comment by ruahman** [comment]
Okay I think I fixed it.  I just had to update the package I had installed.  now it seems to be working

**Comment by Nullarity** [comment]
> Okay I think I fixed it. I just had to update the package I had installed. now it seems to be working

Which package? I have the same problem with the latest nvim and all packages. Already spent hours trying to understand why dapui doesn't load my config, whereas all other plugins do.
