### ISSUE TITLE
Can not jump to code from stack window?

### ISSUE THREAD

**Issue by qianwch** [rcarriga/nvim-dap-ui#119]
How to jump to code from stack window? 
Is it possible to jumping by double click or enter key?

**Comment by rcarriga** [comment]
Yes you can use the `open` mapping (`o` by default)

**Comment by qianwch** [comment]
> Yes you can use the `open` mapping (`o` by default)

Wow, it works charmly!

**Comment by wookayin** [comment]
`open` works well, but I would like to use `<CR>` (mapped to `expand`) which is more intuitive. Is there any way to map `expand` behavior to `open` in the frame stack elements, or override keymap `<CR> = open` in the frame stack element only?

**Comment by JelteF** [comment]
@wookayin FYI this works to override it in the stacks view:
```lua
dapui.setup({
  element_mappings = {
    stacks = {
      open = { "<CR>", "<2-LeftMouse>" },
    }
  },
})
```
