### ISSUE TITLE
stacks.lua:32: attempt to concatenate field 'line' (a nil value)

### ISSUE THREAD

**Issue by danielnehrig** [rcarriga/nvim-dap-ui#12]
i get the following error:

```
Error executing vim.schedule lua callback: ...ack/packer/opt/nvim-dap-ui/lua/dapui/elements/stacks.lua:32: attempt to concatenate field 'line' (a nil value)
Error executing vim.schedule lua callback: ...ack/packer/opt/nvim-dap-ui/lua/dapui/elements/stacks.lua:32: attempt to concatenate field 'line' (a nil value)
```

it will just throw the error debugging works like intended
this happens every time i hit a breakpoint
also scope window is empty stacks says no expressions

i guess this might be my configuration somewhat [link to nvim dotfiles](https://github.com/danielnehrig/.dotfiles-darwin/tree/master/.config/nvim)

this is the config that gets loaded when i lazyload dap
```lua
local dap = require "dap"

dap.adapters.node2 = {
    type = "executable",
    command = "node",
    args = {os.getenv("HOME") .. "/code/vscode-node-debug2/out/src/nodeDebug.js"}
}

vim.fn.sign_define("DapBreakpoint", {text = "🛑", texthl = "", linehl = "", numhl = ""})
vim.fn.sign_define("DapStopped", {text = "🟢", texthl = "", linehl = "", numhl = ""})

dap.configurations.typescript = {
    {
        type = "node2",
        request = "attach",
        program = "${file}",
        cwd = vim.fn.getcwd(),
        sourceMaps = true,
        protocol = "inspector"
    }
}

require("dapui").setup()
```

this is how i attach with lazyloading
```lua
local function attach()
    print("attaching")
    if not packer_plugins["nvim-dap"].loaded then
        vim.cmd [[packadd nvim-dap]]
        vim.cmd [[packadd nvim-dap-ui]]
    end
    require("plugins.dap")
    local dap = require "dap"
    dap.run(
        {
            type = "node2",
            request = "attach",
            cwd = vim.fn.getcwd(),
            sourceMaps = true,
            protocol = "inspector",
            skipFiles = {"<node_internals>/**/*.ts"}
        }
    )
end

return {
    attach = attach
}
```

when nvim loads it wont load dap or dapui
when i press my mapping to trigger the attach() function dap and dapui gets loaded

flow is as follows:
1. Run Neovim
2. press space d h l - to attach to debugger
3. set breakpoints
4. trigger something in app to hit breakpoint
5. when app reaches breakpoint the errors pop up

**Comment by rcarriga** [comment]
OK this should be easy enough to track down. I just need to see what data is being sent from the server.
Please add this line to your config 

```lua
require('dap').set_log_level('DEBUG')
```
and check the log file (probably at `~/.cache/nvim/dap.log`). You might want to remove the existing one to prevent too much noise.

There might be sensitive info in there but all I need to see is the response to the stackTrace request. It'll look something like
```log
[ DEBUG ] 2021-05-19T19:09:51Z+0100 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:712 ]	"request"	{
  arguments = {
    threadId = 1
  },
  command = "stackTrace",
  seq = 9,
  type = "request"
}
[ DEBUG ] 2021-05-19T19:09:51Z+0100 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:486 ]	{
  body = {
    stackFrames = { {
       ...
```
Please paste in the body of the response.

From the error it looks like the `line` attribute isn't being sent which would be annoying because the specification states that it is not optional for a server to send it.

https://microsoft.github.io/debug-adapter-protocol/specification#Types_StackFrame

**Comment by danielnehrig** [comment]
ok give me a second

**Comment by rcarriga** [comment]
Yep that's perfect. I see the issue 
```lua
      }, {
        id = 1050,
        name = "[ async function ]",
        presentationHint = "label"
      }, {
```

It seems the server is inserting these to specify an async function, but I'm not sure how I should display these. Might have to look at how VS code displays to understand what they are meant for. For now anyway I will ignore any frame element without the `line` attribute

**Comment by danielnehrig** [comment]
@rcarriga i can confirm the fix solves the issue
close when ever

**Comment by rcarriga** [comment]
I've
