### ISSUE TITLE
Debug sessions that read user input hang when running consecutive sessions 

### ISSUE THREAD

**Issue by igorlfs** [rcarriga/nvim-dap-ui#120]
I've reproduced this behaviour with both `debugpy` and `lldb-vscode`. 
Reproduction using debugpy: create a sample file that reads input, eg
```python
someData = input()
print(someData)
```
set a breakpoint in the second line (as to not quit the session after reading the input) and start to debug. The first session should work as expected. Start a new session and send input to the console. It will close automatically, and the session will hang. Subsequent sessions will loop between working and hanging. The issue does not happen with bare nvim-dap (ie, without dap-ui).

<details>
  <summary>DAP config for Python</summary>
  
```lua
dap.configurations.python = {
    {
        -- The first three options are required by nvim-dap
        type = "python", -- the type here established the link to the adapter definition: `dap.adapters.python`
        request = "launch",
        name = "Launch file",

        -- Options below are for debugpy, see https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings for supported options
        console = "integratedTerminal",
        program = "${file}", -- This configuration will launch the current file if used.
        pythonPath = "/usr/bin/python"
    },
}
```
</details>

It is **essential to have console set to integratedTerminal** to allow the redirection of input.
Here's the [dap.log](https://gist.github.com/igorlfs/2b068dabd69d30e78206648e95979fca).

**Comment by rcarriga** [comment]
This is a nvim-dap issue, not sure why you're not seeing it without nvim-dap-ui (you might be deleting the buffer between runs?). Anyway I've opened a PR to fix the issue

**Comment by igorlfs** [comment]
> you might be deleting the buffer between runs?

That was it! Sorry to bother 😅
