### ISSUE TITLE
Clean layout after `tabclose`

### ISSUE THREAD

**Issue by przepompownia** [rcarriga/nvim-dap-ui#124]
Hi, this bug exists as long as we introduced expanding long lines but I did not found time to show the reproduction. 

Given https://github.com/przepompownia/dap-ui-test run `make line-hover-extmarks-after-tabclose` and notice that extmarks are not shown up. 

In short, after `tabclose` we can still find buffers used to create UI:

```
:au DAPUIExpandLongLinesForStacks
--- Autocommands ---
DAPUIExpandLongLinesForStacks  CursorMoved
    <buffer=8>
              <Lua function 46>
DAPUIExpandLongLinesForStacks  WinScrolled
    <buffer=8>
              <Lua function 46>
Press ENTER or type command to continue
```
In the above example, if we unhide such orphan buffer (`:sb 8`) into the layout, then we can observe that the old works but its new equivalent - not. 

Given this knowledge the user have to run `dapui.close()` before `tabclose` to make this cleaning at the user side while it is not performed by dap-ui.

**Comment by rcarriga** [comment]
Just checking this and the test seems to show extmarks. Is this still an issue for you?

**Comment by przepompownia** [comment]
Indeed, this test does not give repeatable results. We can close it before making any better test. 

On the other side it would be good to create autocommand on `WinClosed` event to call `dapui.close()`.

In my local environment [I have added `dapui.close()`](https://github.com/przepompownia/vim-arctgx/blob/master/bundleConfig/nvim-dap.lua#L214) to avoid this problem.

**Comment by rcarriga** [comment]
I'm not sure that would make sense for nvim-dap-ui to do. If there's an issue with re-opening the windows then I'd rather fix that instead of assuming how the user wants windows to open/close

**Comment by przepompownia** [comment]
Let's this issue reopen after providing repeatable reproduction.
