### ISSUE TITLE
Deleting an expression in watch won't make it disappear immediately

### ISSUE THREAD

**Issue by gutyina70** [rcarriga/nvim-dap-ui#125]
# Description

When you delete an expression in the watch, part of it may be still rendered until some update happens.

# Steps to reproduce

1. Open a debugging session and go to the expressions window
2. Add an expression
3. Remove that expression

You should see that the expression is still rendered until you press j, go to another window or pretty much do anything that causes a redraw.

# Cause

After digging into the codebase I found out this issue disappears when I comment out the [autocommand for displaying hover info](https://github.com/rcarriga/nvim-dap-ui/blob/b7b71444128f5aa90e4aee8dbfa36b14afddfb7a/lua/dapui/render/canvas.lua#L183-L189).

When you delete an expression, something like this happens:
- vim.schedule-ing the drawing of the hover info
- deleting the expression
- re-rendering only the remaining expressions
- the scheduled hover info draw executes, seemingly the deleted expression reappears

**Comment by rcarriga** [comment]
Thanks for the report and for diving in to figure it out! This should be working now in master
