### ISSUE TITLE
Some unexpanded variables are way too long in the dapui_scopes buffer

### ISSUE THREAD

**Issue by tbttfox** [rcarriga/nvim-dap-ui#129]
I'm debugging some python using using numpy, and the representation of a numpy array includes the **entire** array with newlines for formatting. This means my `(120, 68233, 3)` sized numpy array shows all 24563880 values on 8187960 lines by default without even expanding the variable in the dapui_scopes buffer ... which kinda sucks. (And this is a relatively small size for animated point cloud data)

It looks like the DAP spec has `supportsValueFormattingOptions`, but I don't know if that would help, and it doesn't look like nvim-dap supports that option anyway.

But whether it does or not, I don't think the UI should ever show a bajillion-line representation of any variable by default. At least without some user interaction.

Perhaps you could only show the first X lines of a variable if it's over some threshold?
Then you could either just show the rest of the variable when you expand it, or maybe have some separate line like ` ▸ ... [8187955 more lines]` with some secondary expansion mapping to show the rest.

**Comment by rcarriga** [comment]
I've added a `max_value_lines` option to the render config, with a default of 100. I don't think a mapping to expand the value is needed, since users can just explore the value in the REPL and so it would be relatively complex for little payoff
