### ISSUE TITLE
Function to close dap-ui

### ISSUE THREAD

**Issue by JoseConseco** [rcarriga/nvim-dap-ui#13]
When I run:
`require'dap'.stop()   or  require'dap'.disconnect() `     - added in latest docs commit : https://github.com/mfussenegger/nvim-dap/commits/master/doc/dap.txt
Dap UI wont close. Is there change you could @rcarriga  expose function   ui_dap_close() - so that It could be called manually (in case auto close wont work) ?

**Comment by danielnehrig** [comment]
dap ui windows are closing for me when the adapter is detached
so dap ui works like intended
it sounds like it does not disconnect the adapter on nvim dap in your case

```
stop()                                                              *dap.stop()*
        Closes the current session.
        To disconnect the adapter as well, call |dap.disconnect()| before
        calling |dap.stop()|

disconnect()                                                  *dap.disconnect()*
        Disconnects the adapter from the current session. The session is not
        closed. To close the session, call |dap.stop()|.
 
        Requires an active session.
```

**Comment by JoseConseco** [comment]
You are right - running disconnect first closes the debug-ui. In my case however using disconnect crashes the remote app, so I was  using stop()  - this is why separate function for ui_dap.close() would be nice. But I guess it is not really bug  but more of feature request.  Closing this for now.

**Comment by rcarriga** [comment]
Glad to hear it wasn't a bug in nvim-dap-ui but I've added functions to control the windows manually anyway.

```lua
require("dapui").open()
require("dapui").close()
require("dapui").toggle()
```
