### ISSUE TITLE
Set '[dap-repl]' buffer to 'nobuflisted'

### ISSUE THREAD

**Issue by Vssblt** [rcarriga/nvim-dap-ui#130]
REPL buffer is set to listed by default.
Is there any way to set REPL buffer to unlisted by configuring nvim-dap-ui?

**Comment by rcarriga** [comment]
No nvim-dap-ui does not control the REPL buffer, but you can do 
```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "dap-repl",
  callback = function(args)
    vim.api.nvim_buf_set_option(args.buf, "buflisted", false)
  end,
})
```

**Comment by nyngwang** [comment]
> No nvim-dap-ui does not control the REPL buffer, but you can do [...]

@rcarriga I just encountered the same question/problem: After calling `require('dap').terminate()` I expect all dap-related buffers will be deleted. In the current status, the only buffer left is the one named `[dap-repl]:1`. Are you still recommend creating the `FileType`-autocmd ourselves?
