### ISSUE TITLE
Documentation: Using Watch Expressions

### ISSUE THREAD

**Issue by CharlesARoy** [rcarriga/nvim-dap-ui#131]
I'm new to using debuggers (previously I'd just run my scripts with loads of print statements to figure out where the issues were).

Anyway, I'm trying to figure out how to write watch expressions (for Python) but I'm not sure what the syntax is. Can you provide an example or two?

Thanks so much!

**Comment by rcarriga** [comment]
The expressions are just that, Python expressions. So you can write variables `a` or more complex expressions like `a + b`, `a.some_prop`, `a()` etc. Their value will evaluated every time the debugger steps/stops

VSCode's docs will likely be useful as its using the same underlying tech, it'll just differ in how you control it (i.e. mappings in nvim vs menus in vscode) https://code.visualstudio.com/Docs/editor/debugging

**Comment by CharlesARoy** [comment]
Thanks @rcarriga !

For some reason I was conflating watch expressions with conditional breakpoints which explains why my conditional expressions weren't working 😅

If anyone else stumbles across this, I found this resource to be a bit more comprehensive on watches variables: https://docs.microsoft.com/en-us/visualstudio/debugger/watch-and-quickwatch-windows?view=vs-2022
