### ISSUE TITLE
Define keybindings for debugging only

### ISSUE THREAD

**Issue by zenoli** [rcarriga/nvim-dap-ui#134]
Is it possible to define keybindings that are only active during a debug session?
Vimspector explains how to achieve this here: https://github.com/puremourning/vimspector#custom-mappings-while-debugging

I'm migrating from vimspector and I found it extremely useful to use "J/L/H" for "step-over/step-into/step-out".
Is something similar possible in nvim-dap?

**Comment by zenoli** [comment]
Ok, I think I found a way (no idea if this is a good solution though):

```
function dap_keybind(dap_action, key)
    if require("dap").session() then
        dap_action()
    else
        vim.cmd("normal! " .. key)
    end
end

local map = require("user.utils").map
map("n", "J", function () dap_keybind(dap.step_over, "J") end)
```

**Comment by rcarriga** [comment]
Yep that's exactly how I'd implement it at well :+1: Checking for a session is the best way to know if the debugger is active

**Comment by zenoli** [comment]
Thank for the feedback! This issue can be closed then.
And thank's for the awesome work!
