### ISSUE TITLE
Is there a way to handle ANSI escape codes in the terminal window?

### ISSUE THREAD

**Issue by mwcz** [rcarriga/nvim-dap-ui#136]
My terminal output pane is pretty unusable since my application uses ANSI color codes to colorize text, but they're displayed in unescaped form in the terminal pane.

![image](https://user-images.githubusercontent.com/364615/188533766-bf322f68-7637-44b2-b078-07e92442c226.png)

Is there a way to either remove ANSI color codes entirely, or resolve them into actual colors?

By the way, thanks so much for nvim-dap-ui.  It's been so great having a fully in-context debugger within nvim.  :heart:

**Comment by rcarriga** [comment]
I can't tell from the screenshot, but is that the REPL? The REPL doesn't support ANSI codes (and won't) but if your adapters supports it, you can use the console window. I believe it's usually enabled by `console = "integratedTerminal` in the configuration.

**Comment by mwcz** [comment]
Awesome, thank you.  Setting an [integrated terminal fallback](https://github.com/mfussenegger/nvim-dap/blob/ea25d6d7877558132e11ee9bcf099bf911cb25ac/doc/dap.txt#L432) fixed the problem for me.

```lua
dap.defaults.fallback.external_terminal = {
    command = '/usr/bin/alacritty';
    args = {'-e'};
}
```

(Oh yeah, the screenshot is showing the console pane.)

**Comment by sschneider-ihre-pvs** [comment]
I guess I have the same error in the session view and I have integratedTerminal on already

**Comment by rcarriga** [comment]
I'm not sure what you mean by session view, please open a separate issue.
