### ISSUE TITLE
Just curious how do you set the horizontal line to split windows

### ISSUE THREAD

**Issue by tristone13th** [rcarriga/nvim-dap-ui#137]
In the demo image, you show that you use a single horizontal line to split different windows/elements, how did you achieve that, will you mind sharing your config with me?

**Comment by rcarriga** [comment]
You just need to set `vim.opt.laststatus = 3` and it'll place your statusline at the bottom, using the bars to separate windows instead.

**Comment by tristone13th** [comment]
> You just need to set `vim.opt.laststatus = 3` and it'll place your statusline at the bottom, using the bars to separate windows instead.

Nice, it works!
