### ISSUE TITLE
Feature request: Show breakpoints as a pane

### ISSUE THREAD

**Issue by yingzhu146** [rcarriga/nvim-dap-ui#14]
Hi, 

This idea came out of https://github.com/mfussenegger/nvim-dap/issues/185.

I think it would be very helpful to have a pane showing all active breakpoints. as far as I can tell this isn't available yet as an element. A desired solution would show me breakpoint file number and line and allow easy jumping to it, e.g. via enter/o key

```lua
local elements = {
  STACKS = "stacks",
  SCOPES = "scopes",
  REPL = "repl",
  WATCHES = "watches"
}

```

**Comment by rcarriga** [comment]
Hmm I quite like this idea actually, I'll have at a stab it. Will update once I have something usable

**Comment by rcarriga** [comment]
I've got a version that I think works quite nicely in #15, feel free to try it out and report any feedback. I'll probably merge in a day or two, just want to try it out with multiple servers to make sure I'm not missing anything

**Comment by yingzhu146** [comment]
Awesome, works like a charm thank you!

**Comment by rcarriga** [comment]
Brilliant, merged!
