### ISSUE TITLE
Control Icons not displaying

### ISSUE THREAD

**Issue by medwatt** [rcarriga/nvim-dap-ui#142]
I have everything setup according to the guide. However, I am unable to see the control icons.

Here's how dapui looks like. I'm using the exact configuration you have on the `readme.md` file.

![image](https://user-images.githubusercontent.com/17733465/192056597-6a2cf528-eda5-4e5a-bc19-676d19f97cd2.png)

**Comment by rcarriga** [comment]
This could be a config conflict. What version of neovim are you using? Do you have any `winbar` settings? 

Can you try and reproduce with this minimal `init.lua`
`nvim --clean -u minimal.lua`
```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.stdpath("config"))
vim.opt.packpath:remove(vim.fn.stdpath("data") .. "/site")
vim.opt.termguicolors = true

-- append test directory
local test_dir = "/tmp/nvim-config"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
  vim.cmd("packadd packer.nvim")
  install_plugins = true
end

local packer = require("packer")

packer.init({
  package_root = test_dir .. "/pack",
  compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
  -- Packer can manage itself
  use("wbthomason/packer.nvim")

  use("mfussenegger/nvim-dap")
  use({
    "rcarriga/nvim-dap-ui",
    config = function()
      require("dapui").setup()
    end,
  })

  if install_plugins then
    packer.sync()
  end
end)

vim.cmd([[
command! DapUIToggle lua require("dapui").toggle()
]])
```

**Comment by medwatt** [comment]
> 

With the minimal config, this is what I see:

![image](https://user-images.githubusercontent.com/17733465/192101291-9d5f1835-f878-49bd-a932-e1310302bec2.png)

**Comment by rcarriga** [comment]
Oh I thought that 0.7.2 had the `winbar` feature but apparently not :facepalm: You'll have to use nightly to use it I'm afraid

**Comment by medwatt** [comment]
> Oh I thought that 0.7.2 had the `winbar` feature but apparently not facepalm You'll have to use nightly to use it I'm afraid

I just tried app image of the latest nightly and the icons loaded fine. Thanks for your help!
