### ISSUE TITLE
after i terminate the debugging session,when i debug again,the repl window will move to the left

### ISSUE THREAD

**Issue by HUAHUAI23** [rcarriga/nvim-dap-ui#145]
https://user-images.githubusercontent.com/43649186/192490958-f1136608-f042-4fe8-acc1-9953890f76c1.mp4

**Comment by rcarriga** [comment]
It's an unfortunate side effect of how the window sizes are calculated. As a workaround you can pass `reset = true` to the arguments for `dapui.toggle()` or `dapui.open()`

**Comment by HUAHUAI23** [comment]
yes it's fine,many thanks
i would like to know how reset=true is implemented，i had the same problem at undotree plugin

**Comment by rcarriga** [comment]
Cool :+1: nvim-dap-ui holds the state of the windows before closing them so that it can try and recreate the layout when re-opened. The `reset` option just uses the initial configuration instead of the state to specify the layout
