### ISSUE TITLE
laststatus=0 is not respected

### ISSUE THREAD

**Issue by cunderw** [rcarriga/nvim-dap-ui#146]
Setting laststatus=0 still displays the statusline on all windows. 

I use vimpostor/vim-tpipeline to export lualine to my tmux statusline. 

Is there anyway to disable all window statuslines using nvim-dap-ui?

**Comment by rcarriga** [comment]
nvim-dap-ui doesn' set laststatus anywhere. Setting to `0` works fine for me so this is likely a config issue

**Comment by cunderw** [comment]
This is my dapui config
`dapui.setup({
  icons = { expanded = "▾", collapsed = "▸" },
  mappings = {
    expand = { "<CR>", "<2-LeftMouse>" },
    open = "o",
    remove = "d",
    edit = "e",
    repl = "r",
    toggle = "t",
  },
  expand_lines = false,
  layouts = {
    {
      elements = {
        { id = "scopes", size = 0.25 },
        "breakpoints",
        "stacks",
        "watches",
      },
      size = 40, -- 40 columns
      position = "right",
    },
    {
      elements = {
        "repl",
        "console",
      },
      size = 0.25, -- 25% of total lines
      position = "bottom",
    },
  },
  floating = {
    max_height = nil, -- These can be integers or a float between 0 and 1.
    max_width = nil, -- Floats will be treated as percentage of your screen.
    border = "single", -- Border style. Can be "single", "double" or "rounded"
    mappings = {
      close = { "q", "<Esc>" },
    },
  },
  windows = { indent = 1 },
  render = {
    max_type_length = nil, -- Can be integer or nil.
  },
})`

Setting laststatus=3 works just fine but then my statusline is duplicated in nvim and tmux both. Other windows work with laststatus=0

Any suggestions?

**Comment by rcarriga** [comment]
No I meant your nvim config, not dapui. I don't understand what you mean by other windows work with laststatus=0, do you mean dapui windows have a statusline but other windows don't? Can you provide a screenshot?

**Comment by cunderw** [comment]
If I have dapui open and set laststatus=0 dapui windows and buffers still have the statusline:
![image](https://user-images.githubusercontent.com/29203283/193057234-f413af89-4ab7-4971-9676-8082def14045.png)

If I set laststatus=3 it will move all statuslines to the bottom as expected:
![image](https://user-images.githubusercontent.com/29203283/193057468-b765b2c3-c8aa-42ac-b445-fe7862f2e182.png)

Without dapui open and setting laststatus=0 the statuslines are not displayed except in my tmux status line through vim-tpipeline as expected:

![image](https://user-images.githubusercontent.com/29203283/193058057-2047c6ef-71ef-4c27-877b-70ea804df0df.png)

My full config can be found here: https://github.com/cunderw/nvim

I'm not sure what else could be interfering with dapui.

**Comment by rcarriga** [comment]
I'm sorry but I'm not debugging a config with a tonne of other plugins installed, especially as there is no mention of `laststatus` in nvim-dap-ui except for one place checking if it is set. It's most likely another plugin. I'd suspect lualine as I can see it does set `laststatus`.

I'd be happy to debug if you can reproduce with a minimal init.lua like this 
`nvim --clean -u minimal.lua`

```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.stdpath("config"))
vim.opt.packpath:remove(vim.fn.stdpath("data") .. "/site")
vim.opt.termguicolors = true

-- append test directory
local test_dir = "/tmp/nvim-config"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
  vim.cmd("packadd packer.nvim")
  install_plugins = true
end

local packer = require("packer")

packer.init({
  package_root = test_dir .. "/pack",
  compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
  -- Packer can manage itself
  use("wbthomason/packer.nvim")

  use("mfussenegger/nvim-dap")
  use({
    "rcarriga/nvim-dap-ui",
    config = function()
      require("dapui").setup()
    end,
  })

  if install_plugins then
    packer.sync()
  end
end)

vim.cmd([[
command! DapUIToggle lua require("dapui").toggle()
]])
```

**Comment by cunderw** [comment]
After doing more research, this is a limitation of vim/neovim. You can not remove the statusline, if you have more than two horizontal splits.
