### ISSUE TITLE
[Feature Request]: Open layouts in new tab without original window

### ISSUE THREAD

**Issue by sandersantema** [rcarriga/nvim-dap-ui#152]
I'd like to have dap-ui open some of the layouts like it does by default but open the scopes and repl window separately in a new tab, without the original window which dap is started from. 

I've seen #122 but this opens the original window in a new tab. 

The dap api exposes this functionality:
```lua
local widgets = require('dap.ui.widgets')
local scopes = widgets.scopes
-- Open widget defined as sidebar (although it will occupy the whole window,
-- which is desired) with `tabnew` function.
local sidebar = widgets.sidebar(scopes, {}, 'tabnew')
sidebar.open()
```

But I'd obviously like to have the nice ui of dap-ui :) 

It seems that I might've found a bug using this dap api function as well, which might be of importance for this feature request. When using `widgets.sidebar` with `:tabnew` after opening the sidebar it seems some options are set globally instead of buffer only, `nonumber` is set globally for instance. It might be because it wasn't intended to be used with `:tabnew`. I'll try to post an issue about this in nvim-dap itself asap.

**Comment by rcarriga** [comment]
Sorry I'm not sure what you mean by "original window" but essentially you mean you'd like per-tab layouts, is that right? 

> When using widgets.sidebar with :tabnew after opening the sidebar it seems some options are set globally instead of buffer only, nonumber is set globally for instance.

This could be a side effect of how Neovim core handles options differently depending on how their set, it's a bit of a mess. See https://github.com/rcarriga/nvim-notify/pull/74, https://github.com/neovim/neovim/issues/14595 and linked issues for examples

**Comment by sandersantema** [comment]
I'm missing the correct terminology here but what I mean with original window is the window where from you started the dap session, i.e. the window which displays the buffer with your code and the window where you set your breakpoints in. Let's call this window `w1` and the buffer `b1`.

The approach used in #122 opens a new window call it `w2` displaying buffer `b1` after which dapui is opened. What I would like is to be able to start a dap session in window `w1` open a new window call it `w3`displaying a dapui buffer but not buffer `b1`. What I'm imagining is for instance being able to call `dapui.open({layout = 1, window = <wnum>})` where by convention a window number of `0` would be the current window and default value. 

The following are some niceties but I think if the code would require any changes related to my feature request that would be the best moment to look at some of the api niceties too. It would be nice to take a table for the `layout` option as well, i.e. being able to open multiple layouts at once `dapui.open({layout = {1,2}, window = <wnum>})`. It might even be nice to be able to have the `layouts` table in the config use string keys like:

```lua
layouts = {
  foo = {
    elements = {
      'repl',
    },
    size = 0.25,
    position = 'bottom',
  },
  bar = {
    elements = {
      'watches',
    },
    size = 40,
    position = 'left',
  },
}
```

So one could open the dapui with `dapui.open({layout = {'foo', 'bar'}})` in addition to using indices.

I've looked at the code but I can't really figure out how `dap.open` and the `elements` in `window.layout` relate to the dap widget api of which I know how to open a widget in a new window (the example in my top comment). There's also the `widgets.builder`, could dapui use that or does it not give enough options for customization?

**Comment by rcarriga** [comment]
I'm still a little fuzzy on what exactly you're looking for 
>  What I'm imagining is for instance being able to call dapui.open({layout = 1, window = <wnum>}) where by convention a window number of 0 would be the current window and default value.

Do you mean that a dapui buffer would be placed in the window that is passed in? This is not something that would work with the current code, the opening of the window is important in creating the layout. However you can just write a function that calls `dapui.open` and then closes the original window so you only have dapui windows.

> being able to open multiple layouts at once dapui.open({layout = {1,2}, window = <wnum>})

I don't think I'd be interested in allowing this as you can again just write helper functions around it. I'd prefer to stick with simplicity in the base API.

>  It might even be nice to be able to have the layouts table in the config use string keys

The use of a list is very purposeful as the order matters in how the windows are opened. Using string keys would not work.

It sounds like the only thing required from this is having the ability to open layouts in tabs independently, the rest can be scripted easily enough.

**Comment by sandersantema** [comment]
> It sounds like the only thing required from this is having the ability to open layouts in tabs independently

If I on my turn understood you right I think you do understand me :) That is being able to open layouts in a tab of my choosing independently from the from the buffer which dap is connected to i.e. the tab of my choosing doesn't need to contain a window displaying the buffer but the widgets launched in said tab should be connected to the original dap session.

For example:
- `b1`: buffer containing a file I want to debug say `code.py`
- `t1`: first tab
- `w1`: window in `t1` displaying `b1`
- `t2`: second empty tab created created for the `dap.listeners.after.event_initialized['dapui_config']` event

What I would like to do is start debugging in `w1` and have dap-ui open a layout independently from `b1` in the newly created tab `t2`. What I mean by independently is that `b1` will not be opened in `t2` but the widgets of the layout opened in `t2` should still be connected to the debug session started for `b1` i.e. if a scopes widget is opened in `t2` it should display the variables and such of `b1`.

I hope this made my feature request more clear.

**Comment by rcarriga** [comment]
OK yes that makes it more clear :+1: Though it seems like you don't want to open nvim-dap-ui in multiple tabs, which is the only thing that I thought would be needed. If you just want to not have the original buffer opened then you can just close the window after calling dapui.open
```lua
  local debug_tab = nil

  local function open_in_tab()
    if debug_tab and vim.api.nvim_tabpage_is_valid(debug_tab) then
      vim.api.nvim_set_current_tabpage(debug_tab)
      return
    end

    vim.cmd("tabedit %")
    local debug_win = vim.fn.win_getid()
    debug_tab = vim.api.nvim_win_get_tabpage(debug_win)

    dapui.open()
    vim.api.nvim_win_close(debug_win, true)
  end

  local function close_tab()
    dapui.close()

    if debug_tab and vim.api.nvim_tabpage_is_valid(debug_tab) then
      vim.api.nvim_exec("tabclose " .. vim.api.nvim_tabpage_get_number(debug_tab), false)
    end

    debug_tab = nil
  end

  -- Attach DAP UI to DAP events
  dap.listeners.after.event_initialized["dapui_config"] = function()
    open_in_tab()
  end
  dap.listeners.before.event_terminated["dapui_config"] = function()
    close_tab()
  end
  dap.listeners.before.event_exited["dapui_config"] = function()
    close_tab()
  end
```

**Comment by sandersantema** [comment]
Thanks for the tip! I've got it working but I might have found a bug, if so please let me know and I'll open up a bug report asap.

So this is my working setup and desired result:
```
local function open_in_tab()
  if
    (debug_tab and vim.api.nvim_tabpage_is_valid(debug_tab))
    or (cur_tab and vim.api.nvim_tabpage_is_valid(cur_tab))
  then
    vim.api.nvim_set_current_tabpage(cur_tab)
    return
  end

  local cbuf = vim.fn.win_getid()
  local cur_tab = vim.api.nvim_win_get_tabpage(vim.fn.win_getid())
  vim.cmd.tabedit('%')

  local debug_win = vim.fn.win_getid()
  debug_tab = vim.api.nvim_win_get_tabpage(debug_win)

  dapui.open(3)
  dapui.open(4)

  vim.api.nvim_win_close(debug_win, true)
  vim.fn.win_gotoid(cbuf)
  dapui.open(1)
  dapui.open(2)
end
```

But somewhat confusingly this doesn't: 
```
local function open_in_tab()
  if
    (debug_tab and vim.api.nvim_tabpage_is_valid(debug_tab))
    or (cur_tab and vim.api.nvim_tabpage_is_valid(cur_tab))
  then
    vim.api.nvim_set_current_tabpage(cur_tab)
    return
  end

  local cbuf = vim.fn.win_getid()
  local cur_tab = vim.api.nvim_win_get_tabpage(vim.fn.win_getid())
  -- I would assume these open in the current window i.e. `cbuf`, but somehow they don't and open in `debug_win`.
  dapui.open(1)
  dapui.open(2)

  vim.cmd.tabedit('%')

  local debug_win = vim.fn.win_getid()
  debug_tab = vim.api.nvim_win_get_tabpage(debug_win)

  dapui.open(3)
  dapui.open(4)

  vim.api.nvim_win_close(debug_win, true)
  vim.fn.win_gotoid(cbuf)
end
```

Is this a bug or intended/ too much work to fix?

**Comment by sandersantema** [comment]
I'd consider the bug closed then, thanks for the help and great plugin!
