### ISSUE TITLE
Element-specific key mappings (for dap-repl and dapui_... windows)

### ISSUE THREAD

**Issue by wookayin** [rcarriga/nvim-dap-ui#158]
Can I configure (buffer-local) keymaps for each of the DAP UI elements?

For instance, I would like to map `<CR>` to the `open` action for the "DAP Stacks" element. The current behavior of `<CR>` in this stack frame widget is just a warning message: "No expand action for current line". It would be more intuitive (as a default behavior or for customization) to have `<CR>` mapped to some action, or re-mapped to `o`.

Also, users may want to have a lot of custom key mappings. When it comes to dap-repl, it is possible by making a `FileType` autocmd event as follows:

```lua
  vim.api.nvim_create_autocmd("FileType", {
    pattern = "dap-repl",
    group = ... ,  -- some augroup
    callback = function()
      -- Example: Map CTRL-L to clear the clear REPL
      vim.keymap.set('i', '<c-l>', function() dap.repl.clear() end, { buffer = true, desc = 'Clear REPL' })
      -- and more...
    end,
  })
```

However this does NOT work for **dapui_xxx** elements. Custom keymaps mapped for filetypes `dapui_stacks`, `dapui_watches`, etc. will be lost as dapui would try to reassign the buf-local keymaps during an execution of `dapui.render.canvas.render_buffer()` when the content changes.

**Comment by rcarriga** [comment]
You can now add element specific mappings by adding this to your setup 
```lua
  element_mappings = {
    stacks = {
      open = "<CR>",
      expand = "o",
    }
  },
```

**Comment by wookayin** [comment]
Thank you, that works well for dapui elements.
