### ISSUE TITLE
feat(api) Allow adding expresion to watch 

### ISSUE THREAD

**Issue by przepompownia** [rcarriga/nvim-dap-ui#160]
Similarly to `dapui.eval` it'd be good to can add (especially from visual selection) expression to watches. It seems that currently `Watches:add_watch` is called only for manually typed expressions.

**Comment by przepompownia** [comment]
I did not found the solution in the previous API but in the new API the example
```lua
local function watchExpression(expression)
  dapui.elements.watches.add(expression)
end

api.nvim_create_user_command('DapiUIAddToWatch', function (opts)
  watchExpression(opts.args)
end , {nargs = 1})
```
shows that it's possible :tada:

**Comment by przepompownia** [comment]
In my local env have added both cmd and visualmode:
https://github.com/przepompownia/nvim-arctgx/blob/f2350ce06ccd9fbaf6d5b0891429d9c63be308e5/bundleConfig/nvim-dap-ui.lua#L40-L51

 I suspect that exposing such feature in the way similar to `dapui.eval` would make many users happy.

**Comment by rcarriga** [comment]
Ha didn't even get to post the update before you spotted it, great to hear it being used already :smile: 

> I suspect that exposing such feature in the way similar to dapui.eval would make many users happy.

Great idea, I've added the same ability in the latest commit!

**Comment by przepompownia** [comment]
Thanks. I looked into the change to ensure if it allows selection in both directions :+1: 

It would be good to add some docs about the new feature too.
