### ISSUE TITLE
[Feature Request] Support toggling, rendering of variable type information in locals window

### ISSUE THREAD

**Issue by Swat-SomeBug** [rcarriga/nvim-dap-ui#161]
Thank you for plugin! It works really well for debugging C++.

## Main problem
C++ tends to have very long and complex type names, and it would be good to toggle rending the variable type information, to help reduce noise.
I found [dapui/components/variables.lua](https://github.com/rcarriga/nvim-dap-ui/blob/f889edb4f2b7fafa2a8f8101aea2dc499849b2ec/lua/dapui/components/variables.lua#L56) to render the type info and locally commented the section. The locals window is much more clean.

## Feature request 
The feature request is to have an option (basically a lua call) to toggle rendering type info.
Additionally, there should be a `setup()` option to control the visibility of type information of local variables.
Default -> Always display type info (current status)

Note: The FR does **not** advocate removal of rendering type info. Rendering type info is extremely useful, specially for C++.

To motivate the benefits of the feature please see below the images with the type info turned off vs default:

*With type info (default)*
![image](https://user-images.githubusercontent.com/83545272/199026404-dc87489b-f85d-4181-a2c0-f37c3fb07e0b.png)

*Without type info (additional option requested)*
![image](https://user-images.githubusercontent.com/83545272/199025372-f09f00d9-9c2d-4d7c-8023-f26771ff446c.png)

**Comment by rcarriga** [comment]
> Additionally, there should be a setup() option to control the visibility of type information of local variables.

This is already an option :smile: https://github.com/rcarriga/nvim-dap-ui/blob/f889edb4f2b7fafa2a8f8101aea2dc499849b2ec/README.md#L128

It might make the most sense to allow updating the rendering config via some function e.g. `dapui.setup_render` which can be called multiple times

**Comment by Swat-SomeBug** [comment]
Hi @rcarriga,
Thanks a lot!!
Based on your suggestion, I wrote the following function:
```
function M.toggle_type_info()
  local config = require'dapui.config'
  if config.render().max_type_length == nil then
    config.setup({ render = {max_type_length = 0} })
  else
    config.setup({ render = {max_type_length = nil} })
  end
end
```
and mapped it to an `<leader>dt`, which does what I need.

Questions:
1. Would you consider using `dapui.config` as above a stable API? If not, would you consider adding `dapui.setup_render`? 😃 
2. Is there a way to refresh the `locals` and `watches` windows? Currently, the above function just sets `max_type_length` but doesn't refresh. It takes another event to actually see the types again.

**Comment by rcarriga** [comment]
No only the `dapui` module is public facing. I've added an `update_render` function that will do what you need.
Sample function which you can assign to mapping or command
```lua
  local types_enabled = true
  local toggle_types = function()
    types_enabled = not types_enabled
    dapui.update_render({ max_type_length = types_enabled and -1 or 0 })
  end
```

**Comment by Swat-SomeBug** [comment]
Works well for me! Thank you very much!

**Comment by albertfgu** [comment]
I came across this issue and wanted to chip in a recipe for configuring this in lazy.nvim in case other people come across this thread:
```lua
  {
    "rcarriga/nvim-dap-ui",
    keys = {
      {
        "<leader>dut",
        function()
          local render = require("dapui.config").render
          render.max_type_length = (render.max_type_length == nil) and 0 or nil
          require("dapui").update_render(render)
        end,
        desc = "Toggle types"
      },
    },
  },
```
I'm pretty new to Neovim and Lua configuration so hopefully there aren't any mistakes here, but it seems to work for me!

**Comment by albertfgu** [comment]
I'll also add that I initially tried the following version of the function. Based on the above snippets in the thread and my reading of the documentation, it seemed like you only need to pass in the `max_type_length` variable and then the `dapui.config.render` dictionary will be updated by `update_render()`. But for some reason this didn't work for me - the initial toggle off was fine, but then it wouldn't toggle back on.
```lua
        function()
          local len = require("dapui.config").render.max_type_length
          len = (len == nil) and 0 or nil
          require("dapui").update_render({ max_type_length = len })
        end,
```

**Comment by rcarriga** [comment]
Don't set it to `nil`, use `-1` as shown in the snippet above
