### ISSUE TITLE
toggle and close aren't closing dap-repl buffer

### ISSUE THREAD

**Issue by Fabian-programmer** [rcarriga/nvim-dap-ui#165]
When I close nvim-dap-ui with the close() or toggle command there is still the buffer [dap-repl] open.

```
:buffers
  1 #h   "[No Name]"                    line 1
  4 %a   "[dap-repl]"                   line 1
Press ENTER or type command to continue
```

**Comment by Fabian-programmer** [comment]
Seems to be a nvim-dap problem :) 
Sorry

**Comment by LinHeLurking** [comment]
I'm suffering the same problem. How can I fix it?

**Comment by rcarriga** [comment]
This is intended behaviour. The REPL buffer is supposed to be kept. If you would like to not see it as listed add this to your config:
```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "dap-repl",
  callback = function(args)
    vim.api.nvim_buf_set_option(args.buf, "buflisted", false)
  end,
})
```

**Comment by nyngwang** [comment]
@rcarriga I just encountered the same question/problem: After calling `require('dap').terminate()` I expect all dap-related buffers will be deleted. Could you elaborate more on why you recommended creating the `FileType`-autocmd ourselves?

links #130.
