### ISSUE TITLE
Question: Set float highlight

### ISSUE THREAD

**Issue by elagil** [rcarriga/nvim-dap-ui#166]
My goal is to set the float highlights in some way, for when I call `eval()`.

Currently, it looks to me like a new float uses the `Normal` highlight group - always. Am I misreading this?

https://github.com/rcarriga/nvim-dap-ui/blob/120cb6837206157ab7911ee11ad60986109ce9d6/lua/dapui/windows/float.lua#L102

I wasn't able to tune the appearance of the float by adjusting the `NormalFloat` highlight group (which works for other cases, like `nvim-cmp` floats). How about introducing a new highlight group `DapUINormalFloat`, or using the `NormalFloat` group directly, so that the float background/text can be adjusted independently from the `Normal` group?

The default setting for a potential new `DapUINormalFloat` could be to link it to the `Normal` group, thus not changing the current behaviour.

**Comment by rcarriga** [comment]
Makes total sense, I've linked to `NormalFloat` since that's what should be expected, using `Normal` was purely just because it worked my colorscheme :sweat_smile:
