### ISSUE TITLE
new icons do not display properly even with Nerd font

### ISSUE THREAD

**Issue by meuter** [rcarriga/nvim-dap-ui#169]
Hi

A [recent commit](https://github.com/rcarriga/nvim-dap-ui/commit/1e21b3b50e67700e32285b5a74e645311fd8bbea) introduces new icons for the button used to drive the debugger (start, step-over, step-into, ...). For some reason, these characters do not display properly in Windows Terminal using Nerd font.  The previous set of icons, as well as all the other traditional webdev icons, do display properly with this Font.

Do you have any font recommendation to fix this?

Thanks!

**Comment by rcarriga** [comment]
Yep see https://github.com/rcarriga/nvim-dap-ui/pull/167#issuecomment-1313291149 :smile:

**Comment by meuter** [comment]
Great thanks! I'll have a look
