### ISSUE TITLE
Resize panel splits to original size after closing other splits

### ISSUE THREAD

**Issue by igorlfs** [rcarriga/nvim-dap-ui#175]
Hey there!

I've noticed that when opening a split, like from nvim-tree, closing it makes the left panel's splits larger. Is there any way around this?

**Comment by rcarriga** [comment]
You can call `require("dapui").open({ reset = true })`  to set them back to their configured sizes.

The windows have `winfixwidth` and `winfixheight` set to true which is supposed to prevent this behaviour but it doesn't seem to work for the width. I'm not sure if this is the intended behaviour or if it is a neovim bug

**Comment by igorlfs** [comment]
Hey! After trying multiple events to set up an autocmd, I decided to take a look at nvim-tree's documentation and managed to get it working. Here's the full snippet (in case someone comes across this thread):
```lua
local api = require("nvim-tree.api")
local Event = api.events.Event
api.events.subscribe(Event.TreeClose, function()
    require("dapui").open({ reset = true })
end)
```
Feel free to close this if you want to.

**Comment by Ja-rek** [comment]
This way works:
```lua
local api = require("nvim-tree.api")
local Event = api.events.Event
local function handleTreeEvent()
    local dap = require("dap")
    if dap.session() then
        require("dapui").open({ reset = true })
    end
end

api.events.subscribe(Event.TreeClose, handleTreeEvent)
api.events.subscribe(Event.TreeOpen, handleTreeEvent)

```
