### ISSUE TITLE
Error while opening neovim - Patch Background

### ISSUE THREAD

**Issue by Raagh** [rcarriga/nvim-dap-ui#177]
It seems the last [commit](https://github.com/rcarriga/nvim-dap-ui/commit/f9f85202282abfe1e3d4ff7b5c3c5ae70df0e4f5) has introduced an error on my side. The error happens on line 54 when trying to patch the background of the highlight winbar. It seems I don't have that highlight on my system. Using neovim 0.7

![image](https://user-images.githubusercontent.com/8405459/202859688-67c961d1-cd27-471b-82db-0b3956f178ba.png)

**Comment by Caylub** [comment]
I'm seeing this issue as well: 

```shell
Error detected while processing /home/calebakelley/.config/nvim/init.lua:
...packer/start/nvim-dap-ui/lua/dapui/config/highlights.lua:13: Invalid highlight name: WinBar
E5113: Error while calling lua chunk: ...site/pack/packer/start/onedark.nvim/lua/onedark/init.lua:100:
Vim(lua):E5108: Error executing lua ...packer/start/nvim-dap-ui/lua/dapui/config/highlights.lua:13: Inv
alid highlight name: WinBar
stack traceback:
        [C]: in function 'nvim_get_hl_by_name'
        ...packer/start/nvim-dap-ui/lua/dapui/config/highlights.lua:13: in function 'patch_background'
        ...packer/start/nvim-dap-ui/lua/dapui/config/highlights.lua:54: in function 'setup'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_command'
        ...site/pack/packer/start/onedark.nvim/lua/onedark/init.lua:100: in function 'load'
        /home/calebakelley/.config/nvim/init.lua:23: in main chunk
stack traceback:
        [C]: in function 'nvim_command'
```
after updating `nvim-dap-ui`.

**Comment by Caylub** [comment]
Looks like this is a direct result of the most recent [commit](https://github.com/rcarriga/nvim-dap-ui/commit/f9f85202282abfe1e3d4ff7b5c3c5ae70df0e4f5)

**Comment by rcarriga** [comment]
This should be working in master again, it was an issue for 0.7

**Comment by Caylub** [comment]
Fixed for me! That's a quick response; much appreciated!
