### ISSUE TITLE
Recent update breaks nvim < 0.8

### ISSUE THREAD

**Issue by moosbruggerj** [rcarriga/nvim-dap-ui#181]
The latest release introduced control highlight groups, which are created differently on nvim >= 0.8.

The version check [here](https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/config/highlights.lua#L66) is broken and always executes the 0.8 version, since 0 is true in lua.
This crashes on older nvim versions.

A possible fix is:
```lua
  -- config/highlights.lua:66
  if vim.fn.has("nvim-0.8") ~= 0 then 
```

**Comment by rcarriga** [comment]
Are you using a release build or a nightly build? What does `:echo has("nvim-0.8")` print?

**Comment by AdamHavlicek** [comment]
> :echo has("nvim-0.8")
 prints `0`
> using release build.
using release build (debian)

**Comment by rcarriga** [comment]
This was actually fixed in a separate commit, can you confirm @AdamHavlicek?

**Comment by AdamHavlicek** [comment]
it's now working
