### ISSUE TITLE
Golang can't interactive with terminal

### ISSUE THREAD

**Issue by New-arkssac** [rcarriga/nvim-dap-ui#185]
![image](https://user-images.githubusercontent.com/70094380/203831943-4dcbd22a-7cbd-405a-9089-d7ffeb508479.png)

It doesn't seem to be working
None of the characters I typed were usable in the go program

But the c program does
![image](https://user-images.githubusercontent.com/70094380/203833251-e0df11f0-8c47-4d85-b8e2-4205570535f0.png)

I don't understand. Why is that

> this is my dap-go config
![image](https://user-images.githubusercontent.com/70094380/203832185-9e8ff6e9-683a-4176-a791-54ca8ffafc62.png)

> this is my dap-c config
![image](https://user-images.githubusercontent.com/70094380/203833739-92805cff-228e-4fcc-84b4-f3649d5b2992.png)

> this is my dap-ui config
![image](https://user-images.githubusercontent.com/70094380/203833987-a8b4df80-89a9-4912-82e0-483a841c9c29.png)

**Comment by rcarriga** [comment]
Have you tried setting `console = "integratedTerminal"`? This is more a question for the nvim-dap repo, if that doesn't work I'd suggest checking out the repo and the documentation for the golang adapter first

**Comment by New-arkssac** [comment]
I tried using `console = "integratedTerminal"` and it still didn't work. 
![image](https://user-images.githubusercontent.com/70094380/203958730-b583be86-81bd-4d66-8c5d-aa79e7006d7d.png)

I looked at delve  adapter documentation, and it only had one` --allow-non-terminal-interactive` flag, but that's not what I wanted
![image](https://user-images.githubusercontent.com/70094380/203960292-77e84b1b-ed9a-4978-ac4a-21110cb8874a.png)

> This is more a question for the nvim-dap repo,

Okay, I'll raise the issue
