### ISSUE TITLE
current long line show out of windows

### ISSUE THREAD

**Issue by y1rn** [rcarriga/nvim-dap-ui#186]
![image](https://user-images.githubusercontent.com/70128797/205662641-7c3f288a-c7a4-47f4-960c-a94bf9e5f79e.png)

Is there any buffer option can hide this?

**Comment by rcarriga** [comment]
Set `expand_lines = false` in your config to disable this

**Comment by y1rn** [comment]
> Set `expand_lines = false` in your config to disable this

 thx
