### ISSUE TITLE
Intergate wiht tab plugin

### ISSUE THREAD

**Issue by y1rn** [rcarriga/nvim-dap-ui#187]
I'm using [barbar.nvim](https://github.com/romgrk/barbar.nvim), Is there any setup can correct tabs offset when dap ui open, resize and close?

**Comment by rcarriga** [comment]
Can you clarify your issue? What do you mean by correct tabs offset?

**Comment by y1rn** [comment]
![image](https://user-images.githubusercontent.com/70128797/205778988-d808c50d-6a2d-4528-b998-eb33ce5f14f4.png)
expect
![image](https://user-images.githubusercontent.com/70128797/205779090-d11707ea-ee65-4937-87ff-bff591521bfe.png)

**Comment by rcarriga** [comment]
I believe this needs to be configured by you with barbar. See `:h barbar-integrations`
