### ISSUE TITLE
[NvChad] How to troubleshoot when dapui isn't opening?

### ISSUE THREAD

**Issue by martin-braun** [rcarriga/nvim-dap-ui#189]
I'm trying to use `dapui` in [NvChad](https://github.com/NvChad/NvChad), an enhanced Neovim template.`dap` itself is working so far, I'm loading `dapui` with default values. The Plugin gets downloaded and I get no error when I run `:lua require('dapui').open()`, but nothing else happens, no panels appear.

I put a `print("test")` on the end of the `dapui.open` function (right below `refresh_control_panel()` and it gets printed. 

I understand that I cannot expect support when using a template that handles things differently than the standard, but maybe someone could give me an hint how I could figure out the reason and hunt down the issue, so `dapui` will actually work?

Thanks in advance!

**Comment by rcarriga** [comment]
Have you called the setup function?

**Comment by martin-braun** [comment]
@rcarriga Thank you so much, you are right, I messed up. NvChad uses a different model for configuring plugins, and I had an error in my head, since I thought the setup function will be called automatically, but it's not a generic interface (i.e. `nvim-dap` doesn't want a setup call), so yes, I had to call it myself.

Thanks for the help.
