### ISSUE TITLE
Feature Request:  Specify sidebar window configuration in config

### ISSUE THREAD

**Issue by yingzhu146** [rcarriga/nvim-dap-ui#19]
Hi there,

Would be awesome if we could specify sidebar window configuration. In my opinion, variables should consume much more space than e.g. threads, so I'd like to specify this via config, though I can see that right now it just does splits without specifying the size. Version 2.0 of this feature would allow for persistence of manually resized (e.g. restarting the UI on the same file because I changed the code would not change the window layout which I have adapted in previous run to be well suited to debugging the current setup)

Thanks a ton for this awesome plugin!

**Comment by rcarriga** [comment]
I've been thinking about something similar myself, ideally I'd like to replicate VS Code/IDEs to allow for single key/click expanding/collapsing of windows (in neovim this would be just be a single line height window). Also yes preserving window state across runs would certainly be nice to have!

**Comment by rcarriga** [comment]
Took a while to get to this but you can now specify the proportions of the sidebar for each element. They can also be manually changed and the changes will persist between opening and closing of the sidebar/tray.
