### ISSUE TITLE
Default keymap?

### ISSUE THREAD

**Issue by erlingur** [rcarriga/nvim-dap-ui#192]
I'm not seeing any mention of the default keymap? What keys can I use to step over, step into, etc?

Or does this plugin not provide that?

**Comment by BlueDrink9** [comment]
These commands are provided by [nvim-dap](https://github.com/mfussenegger/nvim-dap), not this UI plugin. This plugin does provide clickable buttons, however

**Comment by erlingur** [comment]
Ah ok, thanks! :) I didn't realise that.
