### ISSUE TITLE
Allow callback function for opened buffers

### ISSUE THREAD

**Issue by BlueDrink9** [rcarriga/nvim-dap-ui#194]
When the Dap UI windows open, it would be great if they could call a function with their buffer number.
The reason for this is to allow us to map our regular DAP keybindings also in the DAP UI windows - e.g. if I'm doing something in the repl, I can press my step mapping to step forwards then continue working. Currently I have to swap back to the window I am debugging to achieve this, because they're buffer-local mappings.

**Comment by rcarriga** [comment]
All of the buffers have their filetype set (e.g. `dapui_scopes`) so you can just use a `FileType` autocommand to do this

**Comment by BlueDrink9** [comment]
Oh, perfect. I wasn't thinking about them in a vim enough way. Got distracted by the `.after` etc functions in this plugin. Works brilliantly, thank you. I'd encourage that to be mentioned in your docs somewhere!
