### ISSUE TITLE
How do you close the floating hover window?

### ISSUE THREAD

**Issue by medwatt** [rcarriga/nvim-dap-ui#197]
When I hover over a variable using `lua require'dap.ui.widgets'.hover()`, a floating window opens. How do I close it? I tied `q` and `ESC`, but neither worked.

**Comment by harrisoncramer** [comment]
If you have focus in the buffer, try `:q` like a normal buffer. You can also add a file to your Neovim configuration to allow `<esc>` to close the buffer (the file must be named ~/.config/nvim/after/ftplugin/dap-float.lua`):

```lua
vim.keymap.set("n", "<esc>", ":q<CR>", {})
```

**Comment by medwatt** [comment]
Thanks for the tip. If I may ask, why not include such a functionality out of the box?

**Comment by medwatt** [comment]
@rcarriga, I was looking at the default configuration in the README and noticed that `q` and `ESC` are supposed to close the floating window. For some reason, pressing these keys doesn't seem to have any effect.  The only way I can make them work is by using the method you suggested. Why is this the case?

```lua
  floating = {
    max_height = nil, -- These can be integers or a float between 0 and 1.
    max_width = nil, -- Floats will be treated as percentage of your screen.
    border = "single", -- Border style. Can be "single", "double" or "rounded"
    mappings = {
      close = { "q", "<Esc>" },
    },
  },
```

**Comment by rcarriga** [comment]
`'dap.ui.widgets'` is provided by nvim-dap. You're looking for `require("dapui").eval` :smile: It will auto close as expected
