### ISSUE TITLE
How to change the width for each elements located at `bottom`?

### ISSUE THREAD

**Issue by nyngwang** [rcarriga/nvim-dap-ui#199]
As title. It seems that currently all elements are opened with equal height & width.

**Comment by rcarriga** [comment]
You can provide the same arguments for all layouts to specify sizes
```lua
        elements = { {id = "repl", size = 0.75}, {id = "console", size = 0.25} },
```

**Comment by nyngwang** [comment]
What happens if those `size`s are not summed up to `1.0`?
