### ISSUE TITLE
Trim stack track path length

### ISSUE THREAD

**Issue by JoseConseco** [rcarriga/nvim-dap-ui#20]
It would be great if path in stack and threads window  would have shorter lengths (maybe as an option):
![image](https://user-images.githubusercontent.com/13521338/120888357-3237a180-c5f8-11eb-9028-d02a80b4d00f.png)
This way user could see the line number.  
One way would be to use file path relative to current project directory:
```lua
rel_file_path = vim.fn.expand("%:p:~:.")
```
Based on   - http://vimdoc.sourceforge.net/htmldoc/cmdline.html#filename-modifiers   

Another thing - it would be cool if <CR> in stack window - would take us to selected line in stack/thread file.

**Comment by rcarriga** [comment]
The path is already supposed to be relative to the CWD, what's the current directory you're in?

You can already go to the frames location by using the `open` keymap (default `o`) to jump to the location

**Comment by JoseConseco** [comment]
my cwd is: 
`/run/media/bartosz/8C343C61343C5086/Users/barto/AppData/Roaming/Blender Foundation/Blender/2.82/scripts/addons/hair_tool/hair_library/`
Maybe the problem is the space in  'Blender Foundation' folder name..  However  in my own code Im using : vim.fn.expand("%:p:~:.")   and it gives correct relative path.  Its good to know about o keymap.

**Comment by rcarriga** [comment]
OK I'm assuming then you're talking about a separate directory to the one you showed in the screenshot, because that could not be displayed relative the CWD you just gave. 

Can you try with the latest commit? I've added a small fix which might be the cause, though I'm not sure

**Comment by JoseConseco** [comment]
I just updated but  I saw no change.  I think the problem is that I use project that has linked directory  in its structure.
![image](https://user-images.githubusercontent.com/13521338/120902863-12799b00-c643-11eb-85a0-ee02d46673e1.png)
The bottom line - shows cwd - it is the 'real' project location. The threads window shows structure as 'seen' by python?  I'm not sure.  I any case, maybe after making path relative, you could trim relative_path  up to max 15 characters (or leave only file name if rel_path is too long) ?  IMO it is more usefull to see file name and line number than the whole path.

**Comment by JoseConseco** [comment]
Thanks update works  great.!
