### ISSUE TITLE
Error: attempt to perform arithmetic on local 'win_size' (a nil value)

### ISSUE THREAD

**Issue by deankinane** [rcarriga/nvim-dap-ui#200]
Hi

I'm receiving this error the first time the UI loads after opening Vim.
It happens once for each side panel layout, but not for the bottom layout.

It only occurs after I modified the config, if I just setup() with no custom config there is no error.

Here is my config:
```
{
    layouts = {
        {
            elements = {
                { id = 'scopes', size = 0.75 },
                { id = 'watches' },
        },
        size = 50,
        position = 'left'
    },
    {
       elements = {
           'breakpoints',
       },
       position = 'right',
       size = 20
    },
    {
        elements = {
            { id = 'repl' },
        },
           size = 0.25,
           position = 'bottom'
        }
   },
}
```
Here is the error:
![Screenshot_20221229_182918_Termux~2](https://user-images.githubusercontent.com/22434814/209995641-15e4f0af-18b6-409b-9097-2405693d527c.jpg)

After I dismiss the error everything appears to load and work perfectly fine.

Appreciate your help with this.

**Comment by rcarriga** [comment]
> { id = 'repl' },

> { id = 'watches' },

You have to specify a `size` field if using a table or just provide `"repl"` and `"watches"` directly to avoid the issue. Though if you're specifying a size for one element in a layout, all elements in that layout should have a size field to guarantee correct sizing.

**Comment by deankinane** [comment]
Thanks, that solved the issue!
