### ISSUE TITLE
console issuses

### ISSUE THREAD

**Issue by y1rn** [rcarriga/nvim-dap-ui#204]
1. how to setup console element auto scroll to bottom
2. console output auto wrap.  which causes resize console panel and copy console text with wrap

**Comment by rcarriga** [comment]
I've added autoscrolling to the console (using the solution from https://github.com/mfussenegger/nvim-dap/pull/654) so as long as the cursor is on the last line of the buffer, it will autoscroll, similar to a terminal.

Terminal wrapping is not controlled by nvim-dap-ui. There are some issues with it in Neovim https://github.com/neovim/neovim/issues/2514

**Comment by y1rn** [comment]
cool, thx
