### ISSUE TITLE
Text shown outside floating window

### ISSUE THREAD

**Issue by Bekaboo** [rcarriga/nvim-dap-ui#206]
With this configuration (max width limited to 40), text in floating windows will be displayed outside the border.

```lua
dapui.setup({
    icons = {
      expanded = '▼',
      collapsed = '►',
      current_frame = '►',
    },
    mappings = {
      -- Use a table to apply multiple mappings
      expand = { '<Tab>', '<LeftMouse>' },
      open = { '<CR>', 'o' },
      remove = { 'dd', 'x' },
      edit = 'e',
      repl = 'r',
      toggle = '<Leader><Leader>',
    },
    floating = {
      max_height = 20,
      max_width = 40,
      mappings = {
        close = { 'q', '<Esc>' },
      },
    },
    windows = { indent = 1 },
  })
```
![Screenshot_20230113_230600](https://user-images.githubusercontent.com/76579810/212456938-d5040ded-33ab-4927-9af1-69844543c325.png)

Text will also stick out of normal windows, for example, this is how DAP watches window looks like when current line is too long:
![image](https://user-images.githubusercontent.com/76579810/212457098-97e17eee-1616-45a6-bfe1-493e99dfa732.png)

**Comment by adventcoder0** [comment]
This is my first time commenting on a github issue. I don't use floating windows but I use the normal windows and I was able to fix/work around the text issue by setting expand_lines to false in my setup. Maybe that will fix it for you as well.

`require("dapui").setup({
  expand_lines = false;
})
`

I apologize if this doesn't help, I am still a little new to using nvim and dap.

**Comment by Bekaboo** [comment]
> 

Hi, thank you for your comment! Setting `exapnd_lines` to false solves the issue.
