### ISSUE TITLE
Expanding some expressions triggers gibberish text to be inserted on step

### ISSUE THREAD

**Issue by igorlfs** [rcarriga/nvim-dap-ui#210]
This is a bit odd to explain. I'm watching an expression. When I try to expand it, it does work, but part of the expression gets inserted in the watch prompt, like so
![image](https://user-images.githubusercontent.com/84649544/213594389-2931903a-58be-4167-a44d-ac9e50a22c3e.png)
But the odd part is that when I try to step over, for instance, a bunch of text is inserted in the code (not a DAP buffer), mostly repeating the snippet inserted in the watch prompt. I would have screenshotted this, but I quit Neovim, and now it's working as usual again, so it's not really reproducible. Has anyone had a similar experience?

**Comment by rcarriga** [comment]
I've not seen anything like this before. Unfortunately I can't do much without being able to reproduce. Has it happened since?

**Comment by igorlfs** [comment]
Nope, I haven't been able to reproduce since

**Comment by igorlfs** [comment]
I'll be closing this as I haven't seen this issue in a while but if I manage to find a reproduction, I'll reopen.
