### ISSUE TITLE
dap-repl buffer opens with nvim

### ISSUE THREAD

**Issue by duarm** [rcarriga/nvim-dap-ui#214]
I'm on b3b977095877e8acc1ff236cffc81b5331619493, before that commit, all dap-ui buffers would be opened, that commit almost fixes the problem, it unlists every dap-ui buffer, except the repl one

```
$ nvim
```
![image](https://user-images.githubusercontent.com/26150581/214955193-4c7b0610-e0f3-48f1-9714-2a550b4983df.png)

**Comment by edward-s** [comment]
same issue

**Comment by rodhash** [comment]
same here .. b80227e seems to be fine so locking my packer on this one meanwhile

**Comment by rcarriga** [comment]
Instead of rolling back, you can use this workaround https://github.com/rcarriga/nvim-dap-ui/issues/165#issuecomment-1377712562

**Comment by duarm** [comment]
fixed by https://github.com/mfussenegger/nvim-dap/pull/839
