### ISSUE TITLE
Failed to call open() when debug session restarted

### ISSUE THREAD

**Issue by ray-x** [rcarriga/nvim-dap-ui#218]
linked issue:
https://github.com/ray-x/go.nvim/issues/278

Stack trace
```
Error executing Lua callback: ...ck/packer/start/nvim-dap-ui/lua/dapui/windows/layout.lua:37: Invalid buffer id: 4
stack traceback:
        [C]: in function 'nvim_set_current_buf'
        ...ck/packer/start/nvim-dap-ui/lua/dapui/windows/layout.lua:37: in function 'open'
        ...im/site/pack/packer/start/nvim-dap-ui/lua/dapui/init.lua:354: in function 'cb'
        ...im/site/pack/packer/start/nvim-dap-ui/lua/dapui/init.lua:280: in function 'keep_cmdheight'
        ...im/site/pack/packer/start/nvim-dap-ui/lua/dapui/init.lua:332: in function 'open'
        ...share/nvim/site/pack/packer/start/go.nvim/lua/go/dap.lua:358: in function 'run'
```
The issue happened from version `d608b7628aeafa36cf5e3439def832e9789b7ff8` 

It works fine for the first debug session.  When debug session stop, I will call `require'dapui'.close()`

When I start debug session next time. As all layout is_open() are false, I will call open() again. And at that time I saw above errors.

Also when stop, there are warnings:
```
Rendering failed: .../packer/opt/nvim-dap-ui/lua/dapui/components/threads.lua:63: attempt to index field 'session' (a nil value)
stack traceback:
	...nvim/site/pack/packer/opt/nvim-dap-ui/lua/dapui/util.lua:17: in function '__index'
	.../packer/opt/nvim-dap-ui/lua/dapui/components/threads.lua:63: in function 'render'
	...ack/packer/opt/nvim-dap-ui/lua/dapui/elements/stacks.lua:31: in function 'render'
	...ack/packer/opt/nvim-dap-ui/lua/dapui/elements/stacks.lua:19: in function <...ack/packer/opt/nvim-dap-ui/lua/dapui/elements/stacks.lua:18>
	[C]: in function 'xpcall'
	...nvim/site/pack/packer/opt/nvim-dap-ui/lua/dapui/util.lua:16: in function <...nvim/site/pack/packer/opt/nvim-dap-ui/lua/dapui/util.lua:12>
```

Please comment if I needed to pass in specific arguments to open() and close(). Thanks!

**Comment by rcarriga** [comment]
I've put in a fix for the failed rendering warning, but couldn't reproduce the first issue. Can you try with the latest commits and check again? If there is still an issue I'll need a minimal init.lua to reproduce

**Comment by ray-x** [comment]
Thanks, the warnings were gone. But still failed to open dapui()

to reproduce, here is a minium vimrc:

https://github.com/ray-x/go.nvim/blob/master/playground/init.lua

go.nvim will wrap dap/dapui
So you need to open a simple go source file, e.g
https://github.com/ray-x/go.nvim/blob/master/playground/sampleApp/main.go

nvim -u ../init.lua  main.go
Set break with : GoBreakToggle
Start debug: GoDebug
Stop debug: GoDebug -s
Restart debug: GoDebug

And you should see the errors.

**Comment by nyngwang** [comment]
FYI: I did experience the second warning. Thanks for the report.

**Comment by rcarriga** [comment]
Thanks for the reproduction! The issue was caused by `go.nvim` closing the REPL without using the toggle mode, which deletes the buffer. This is now handled in the latest commit :smile:

**Comment by ray-x** [comment]
Thanks, new version fixed the issue.
