### ISSUE TITLE
nvim-dap-ui may make nvim-dap not work correctly.

### ISSUE THREAD

**Issue by pittcat** [rcarriga/nvim-dap-ui#22]
You can find detailed information here.https://github.com/Pocco81/DAPInstall.nvim/issues/4

**Comment by mfussenegger** [comment]
Tl:Dr version: vscode-cpptools chokes on threads requests with `{}` as argument.  `nil` works. See

https://github.com/rcarriga/nvim-dap-ui/blob/7564f9163b786af1a2bb251385d634ef860d5d33/lua/dapui/elements/stacks.lua#L144

**Comment by rcarriga** [comment]
Ah thank you for the info! @pittcat please try with the latest commit

**Comment by pittcat** [comment]
I have tried latest version, and the previous problem disappeared. But a new error message will appear.
Error info:
```
Source not available, cannot jump to frame
Error executing vim.schedule lua callback: ...m/plugged/nvim-dap-ui/lua/dapui/elements/breakpoints.lua:66: attempt to index field 'source' (a nil value)
```

**Comment by pittcat** [comment]
https://asciinema.org/a/Tcmz7QFmK6sD0Ksgo83FWacSP

**Comment by rcarriga** [comment]
Ah separate issue, please try with latest

**Comment by pittcat** [comment]
The latest version fixed the issue. Thank you.
