### ISSUE TITLE
Interface does not open through ssh

### ISSUE THREAD

**Issue by astahjmo** [rcarriga/nvim-dap-ui#221]
I have been using nvim-dap-ui for a long time on my local machine but sometimes I need to access another machine remotely using ssh, and this remote machine has the same configuration as my local machine but for some reason the nvim-dap-ui interface doesn't show up, no errors, no messages, nothing happens calling  `:lua require("dapui").open()`  on an ssh connection

**Comment by rcarriga** [comment]
I'm afraid I can't be much help without a reproducible config. My guess would be that the dapui setup function isn't called, which leads to the `open` function having no effect
