### ISSUE TITLE
repl send scope variables to code file buffer instead of repl window

### ISSUE THREAD

**Issue by huyiqun** [rcarriga/nvim-dap-ui#223]
Thanks for the great plugin! I am using this for python debug and I ran into the following problem, not sure if I am missing any settings. When I have cursor in the `scopes` window and press `r`, which is mapped to send variable to repl, the variable is sent to code file buffer instead of the repl.

I have tried a couple of different config. Here is how to replicate: I am using https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua as the basic config, with these plugins added

```
use 'mfussenegger/nvim-dap'
use "jayp0521/mason-nvim-dap.nvim"
use 'mfussenegger/nvim-dap-python'
use { "rcarriga/nvim-dap-ui", requires = {"mfussenegger/nvim-dap"}}
use 'theHamsta/nvim-dap-virtual-text'
```
for `Packer` and I added these lines for a simple setup:
```
local dap, dapui = require('dap'), require('dapui')
require("mason-nvim-dap").setup({
  ensure_installed = { "python" }
})

require('dap-python').setup('~/.pyenv/shims/python')

dap.listeners.after.event_initialized["dapui_config"] = function()
dapui.open()
end

dap.listeners.before.event_terminated["dapui_config"] = function()
dapui.close()
end

dap.listeners.before.event_exited["dapui_config"] = function()
dapui.close()
end

dapui.setup {
  element_mappings = {
    scopes = {
      repl = "r",
    },
  },
}
```
Let's say I put cursor on the `this_is_a_list` variable line in the `scopes` window and press `r`
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/10877536/215630429-c570de6f-72f0-42f5-a633-7bdd03155845.png">

It inserts `this_is_a_list` in the code buffer instead of sending it to the repl window (the lower right corner) for evaluation.
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/10877536/215630532-45e00224-2d6a-41dd-b18c-509e1374a5a5.png">

Am I missing anything here?

**Comment by rcarriga** [comment]
Ah it was an non-escaped pattern issue, should be working now :smile:

**Comment by huyiqun** [comment]
working now, thanks for the fix!    😃
