### ISSUE TITLE
Feature Request: Add disconnect to the dap-repl

### ISSUE THREAD

**Issue by mikesmithgh** [rcarriga/nvim-dap-ui#225]
I have recently started debugging with dlv (https://github.com/go-delve/delve) and have a use case where I am debugging remotely. I would like to disconnect rather than terminate the debug session. I am able to do this by calling nvim-dap directly, but would like the option for an icon to disconnect.

dlv has the ability for a multi-client mode (https://github.com/go-delve/delve/blob/master/Documentation/api/dap/README.md#launch-and-attach-configurations)
```
dlv --headless --accept-multiclient=true
```
This allows me to disconnect and reconnect the debug session.

## Feature request: 
Add disconnect icon and action to the to dap-repl.
Source: https://github.com/rcarriga/nvim-dap-ui/blob/ed2c345fa8edd3f6049b9647a74a5d8cc5318ce3/lua/dapui/config/init.lua#L122
![dap-ui-repl](https://user-images.githubusercontent.com/10135646/215682125-b14ab935-df8b-4243-a339-e647fc77e90d.png)

Thanks!

**Comment by rcarriga** [comment]
Done in latest master :smile:

**Comment by mikesmithgh** [comment]
![Screenshot 2023-02-07 at 7 53 31 AM](https://user-images.githubusercontent.com/10135646/217250518-17f6b804-726b-43c2-b991-62f6d46b6462.png)
Looks good to me, Thanks! :shipit: 👍
