### ISSUE TITLE
REPL floating window does not open REPL

### ISSUE THREAD

**Issue by RonanMacF** [rcarriga/nvim-dap-ui#23]
executing `:lua require'dapui'.float_element("repl")` does not appear to open a reply but just a blank floating window.

[asciicinema](https://asciinema.org/a/3qiM3oNlaXJh0io6Az2gkS7kB)

**Comment by rcarriga** [comment]
Ah yeah that's because it's the nvim-dap repl which doesn't work in multiple windows. Not much I can do about that I'm afraid. You already have it open in the tray at the bottom. If you remove the repl from your tray elements, it should work.

**Comment by RonanMacF** [comment]
ah I see, the workfflow I think which would work nice for me which I tested and works is 

- Have it in the tray by default and open on start
- If you want to see more code you can toggle it using `lua require('dap').repl.toggle()`
- if you want a quick glance at the repl you can call the floating window which works
- if you want a deeper look at the repl you can close the floating window and call `lua require('dap').repl.toggle()` again which brings it back in the tray

**Comment by rcarriga** [comment]
That works as far I can tell so are you happy to close this?
