### ISSUE TITLE
Local Variables Collapse On Stepping/Continuing

### ISSUE THREAD

**Issue by BrendanNolan** [rcarriga/nvim-dap-ui#230]
# Issue
When I step/continue in nvim-dap-ui, my expanded local/watched variables are automatically collapsed. Can I configure nvim-dap-ui to keep my expansions after I step/continue?

## Example
Here is some rust code where I have a vector of vectors and I want to see the internals - i.e. I want to see everything in the outer and inner vectors. I can expand the variable `v` in the `Locals` and `Watches` views, as you can see on the left of this screenshot:
![Screenshot from 2023-01-27 18-24-07](https://user-images.githubusercontent.com/33930501/216650099-aaabf4b5-068d-4b58-8e57-d2a36bda85c4.png)

However, when I step or continue in the debugger, `v` is automatically collapsed in the `Locals` and `Watches` views, as you can see in the below screenshot:
![Screenshot from 2023-01-27 18-26-37](https://user-images.githubusercontent.com/33930501/216650944-dfb4c0a5-8c43-491b-862e-40431b138a5e.png)

Below is my dapui config:
```lua
require("dapui").setup()

local dap, dapui = require("dap"), require("dapui")
dap.listeners.after.event_initialized["dapui_config"] = function()
  dapui.open()
end

vim.keymap.set("n", "<leader>cdb", dapui.close)

```

**Comment by rcarriga** [comment]
Can you provide a debug log for nvim-dap so I can see what data is being sent? See `:h dap.set_log_level()` for setting the level and to get the log location

**Comment by BrendanNolan** [comment]
> Can you provide a debug log for nvim-dap so I can see what data is being sent? See `:h dap.set_log_level()` for setting the level and to get the log location

Yes absolutely. I'll do that tomorrow at the latest.

So this collapsing is not normal behaviour? Usually the user's expansions persist after stepping/continuing?

**Comment by rcarriga** [comment]
Correct, the variables should remain expanded :+1: The logic is based on the variable names so I'm not sure what would reset that

**Comment by BrendanNolan** [comment]
Thanks Rónán. Here's that debug log.

[dap_debug_log.log](https://github.com/rcarriga/nvim-dap-ui/files/10735734/dap_debug_log.log)

**Comment by rcarriga** [comment]
Ah I see the issue, the frame ID does not remain the same across steps for your adapter. For each frame, we use the frame ID to know what variables to keep expanded (so users can jump between frames and keep the expanded state without mixing them up e.g. common variable names).

Looks like VSCode doesn't take the frame into account when storing expanded state, which IMO is a bit confusing but the spec doesn't allow for using frame ID so I've made the change to also ignore it. 

Please try the latest commit and it should work :smile:

**Comment by BrendanNolan** [comment]
> Ah I see the issue, the frame ID does not remain the same across steps for your adapter. For each frame, we use the frame ID to know what variables to keep expanded (so users can jump between frames and keep the expanded state without mixing them up e.g. common variable names).
> 
> Looks like VSCode doesn't take the frame into account when storing expanded state, which IMO is a bit confusing but the spec doesn't allow for using frame ID so I've made the change to also ignore it.
> 
> Please try the latest commit and it should work smile

The latest commit does the job! This is fixed on my end now. Cheers lad! (I don't know what the normal procedure is for closing issues -  should I close it as the reporter?)

**Comment by rcarriga** [comment]
Normally I leave to the reporter just in case I missed something :smile: But happy to close now that the fix is confirmed

**Comment by BrendanNolan** [comment]
> Normally I leave to the reporter just in case I missed something 😄 But happy to close now that the fix is confirmed

Grand. Thanks!
