### ISSUE TITLE
Text in panes don't wrap

### ISSUE THREAD

**Issue by Kindlewing** [rcarriga/nvim-dap-ui#235]
Is there a way to make the text in a pane wrap, or enlarge the pane when  the text overflows?
Below is a screenshot
![Wrap](https://user-images.githubusercontent.com/28827961/217574967-2c691eb8-bee3-4d92-8c86-a201a5661a26.png)

in the DAP Scopes pane, the text overflows. There's other examples on that screenshot too.

**Comment by Kindlewing** [comment]
I figured out a way around this. Closing

**Comment by theoribeiro** [comment]
@Kindlewing how did you work around the text overflowing in the scopes window?

**Comment by Alexey104** [comment]
I am also curious is it possible to enable text wrapping? Not `expand_lines`, but wrapping.
@theoribeiro, did you find the solution?

**Comment by theoribeiro** [comment]
Nope, couldn't find a solution yet, unfortunately :(

**Comment by Alexey104** [comment]
The only solution I found is to manually change line 180 from `wrap = false` to `wrap = true` in `~/.vim/plugged/nvim-dap-ui/lua/dapui/windows/layout.lua`. Maybe there is a better way of doing this, but I don't really understand this Lua stuff well enough.

**Comment by diegocmsantos** [comment]
This works perfectly @Alexey104 
thanks for that
I wonder if there is a way to do it using the nvim-dap-ui plugin options

**Comment by b11e** [comment]
> The only solution I found is to manually change line 180 from `wrap = false` to `wrap = true` in `~/.vim/plugged/nvim-dap-ui/lua/dapui/windows/layout.lua`. Maybe there is a better way of doing this, but I don't really understand this Lua stuff well enough.

thanks,

if lazyvim
`nvim ~/.local/share/nvim/lazy/nvim-dap-ui/lua/dapui/windows/layout.lua`
