### ISSUE TITLE
dap-repl window width is not correct after trigger debug session twice

### ISSUE THREAD

**Issue by pdckxd** [rcarriga/nvim-dap-ui#236]
NVIM: `v0.8.3`
nvim-dap-ui: `commit 100c67dd63c870819fb998fec4867b17d02db4b7`
iTerm 

1. call :DapContinue to launch the dap-ui
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/1890394/218505901-be8ec635-a4a8-4e9c-b562-df5ccb9f777e.png">
2. call :DapTerminate to stop debug session and close dap-ui
3. call :DapContinue to launch the dap-ui again
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/1890394/218505717-f11ff3c0-9a42-4e83-85aa-9d5785b0c675.png">

* Config
```lua
local status_ok, dapui = pcall(require, "dapui")
if not status_ok then
    vim.notify("dapui not found")
    return
end

local config = {
    controls = {
        element = "repl",
        enabled = true,
        icons = {
            disconnect = "",
            pause = "",
            play = "",
            run_last = "",
            step_back = "",
            step_into = "",
            step_out = "",
            step_over = "",
            terminate = "",
        },
    },
    element_mappings = {},
    expand_lines = true,
    floating = {
        border = "single",
        mappings = {
            close = { "q", "<Esc>" },
        },
    },
    force_buffers = true,
    icons = {
        collapsed = "",
        current_frame = "",
        expanded = "",
    },
    layouts = {
        {
            elements = {
                {
                    id = "scopes",
                    size = 0.25,
                },
                {
                    id = "breakpoints",
                    size = 0.25,
                },
                {
                    id = "stacks",
                    size = 0.25,
                },
                {
                    id = "watches",
                    size = 0.25,
                },
            },
            position = "left",
            size = 40,
        },
        {
            elements = {
                {
                    id = "repl",
                    size = 0.5,
                },
                {
                    id = "console",
                    size = 0.5,
                },
            },
            position = "bottom",
            size = 10,
        },
    },
    mappings = {
        edit = "e",
        expand = { "<CR>", "<2-LeftMouse>" },
        open = "o",
        remove = "d",
        repl = "r",
        toggle = "t",
    },
    render = {
        indent = 1,
        max_value_lines = 100,
    },
}

dapui.setup(config)
```

**Comment by rcarriga** [comment]
You haven't included the event listeners that open the UI but there was a bug where the `reset` option wasn't being respected. If you're not passing `reset` to `open` then I'd recommend doing so.

I'm not sure why the window changes size like that but as I'm planning on switching to nui.nvim at some stage, I likely won't be addressing it directly

**Comment by pdckxd** [comment]
> You haven't included the event listeners that open the UI but there was a bug where the `reset` option wasn't being respected. If you're not passing `reset` to `open` then I'd recommend doing so.
> 
> I'm not sure why the window changes size like that but as I'm planning on switching to nui.nvim at some stage, I likely won't be addressing it directly

Very Cool! It works now.
