### ISSUE TITLE
Open/Toggle with `reset = true` not completely resetting layout.

### ISSUE THREAD

**Issue by AlexSWall** [rcarriga/nvim-dap-ui#237]
On opening dap-ui, my default layout is the following.

<img width="1436" alt="before" src="https://user-images.githubusercontent.com/31999802/218612026-19429e3f-bc3e-469c-b1a6-5cf679c8f950.png">

However, if I resize some of the panes, on toggling/closing and opening dap-ui with `{ reset = true }`, the UI is not reset, and panes remain in their modified positions/shapes.

<img width="1440" alt="after" src="https://user-images.githubusercontent.com/31999802/218612103-2c01709d-e80f-4812-af3d-6495ccae86ba.png">

Is there a way to completely reset the UI to avoid any resizing that may have accidentally occurred?

**Comment by rcarriga** [comment]
Should be working as expected now :smile:
