### ISSUE TITLE
floating window should expand if possible

### ISSUE THREAD

**Issue by RonanMacF** [rcarriga/nvim-dap-ui#24]
When the floating window height is set to a large number, e.g. 1.0, or 0.9, I would expect it to fill the grow up to this size to show all variables if possible.

The recording [here](https://asciinema.org/a/dts8RRr06xcaM0M0ig3Bl8ZUm) shows that it could grow slightly to show all the variables but it doesn't, giving the impression that the height value is being ignored.

**Comment by rcarriga** [comment]
That looks like the `wrap` setting is being turned on, which it should not be. Do you have some autocommand that sets it? NeoVim doesn't provide any way to know the length of a window that is wrapped unfortunately so if you wanted to keep wrapping, there's no way the window will always fit correctly

**Comment by RonanMacF** [comment]
`rg wrap` shows no augroup for wraps. 

You see it's interesting because the sidebar `dapui_Scopes` is successfully being set to `nowrap` but the floating window isn't. If there was some setting in my config then I would have thought it would have applied to both.

Anyways I can make a autocommand to set `nowrap` on dapui buffer enter so there is a workaround. Incase it is a bug I will leave it open for you to close, if your confident it's an issue somewhere with me go ahead and close, thanks

**Comment by rcarriga** [comment]
Well this is embarassing... I had a typo in the code and wasn't setting it correctly 😅 Fixed now!
