### ISSUE TITLE
Can't leave the terminal with the keyboard with program prompts a value

### ISSUE THREAD

**Issue by ebiscaia** [rcarriga/nvim-dap-ui#243]
Hi,

I am having the following problem:

I wrote a program that prompts the user some input, then started the debugging process. I went to the terminal and inserted some value and pressed Enter. If I try to use my navigation keys (Ctrl+[h,j,k,l]) it shows ^[H,J,K,L]. I can only use the mouse to leave the terminal window or use the controls to continue debugging.

I used the dapui.settings({}) to check whether was a setting of mine that was the problem.

Thanks,

**Comment by rcarriga** [comment]
The console window is a terminal buffer which means you have to use terminal mode mappings (e.g. `:tnoremap`. See `:h terminal-mode`

**Comment by ebiscaia** [comment]
Thanks,

I think I set some keymappings to make it more natural to my workflow.

**Comment by ebiscaia** [comment]
If anyone bumps into this issue:

Go to where you set your keybindings and make sure you have these lines:
```
keymap("n", "<C-h>", "<C-w>h", opts)                                                                                      
keymap("n", "<C-j>", "<C-w>j", opts)                                                                                      
keymap("n", "<C-k>", "<C-w>k", opts)                                                                                      
keymap("n", "<C-l>", "<C-w>l", opts)
```

Those lines allow to navigate the windows using Ctrl+{h,j,k,l} instead of Ctrl+w followed by those keys in normal ("n") mode. After that, somewhere in the same file add the following ones:
```
keymap("t", "<C-h>", "<C-\\><C-N><C-h>", opts)                                                                            
keymap("t", "<C-j>", "<C-\\><C-N><C-j>", opts)                                                                            
keymap("t", "<C-k>", "<C-\\><C-N><C-k>", opts)                                                                            
keymap("t", "<C-l>", "<C-\\><C-N><C-l>", opts)
```

What these line do is in terminal ('t') mode when pressed Ctrl+{h,j,k,l}, first goes to normal mode <C-\><C-N> and then applies the keybinding previously set in normal mode.
