### ISSUE TITLE
Attempt to concatenate data a table value error, unable to start dap ui

### ISSUE THREAD

**Issue by asmodeus812** [rcarriga/nvim-dap-ui#245]
![image](https://user-images.githubusercontent.com/15955811/222723816-152b24a4-e35b-44b4-82dd-43b9004fc6fb.png)

**Comment by rcarriga** [comment]
Can you describe what breakpoints you have active when this happens?

**Comment by asmodeus812** [comment]
Yes, sorry it was an issue with passing in empty table (not nil) to the set breakpoints api in dap, i think we can close this, but could also consider if we should maybe guard against that.
