### ISSUE TITLE
Dap scopes ui overuns window size

### ISSUE THREAD

**Issue by luisjakon** [rcarriga/nvim-dap-ui#246]
When trying expanding the info, the text goes outside its defined window...

<img width="1027" alt="Screenshot 2023-03-03 at 2 25 47 PM" src="https://user-images.githubusercontent.com/6248573/222809019-e50303bd-e407-4b60-b6d0-c9b4b5d15d41.png">

**Comment by rcarriga** [comment]
Set `expand_lines = false` in the setup table :smile:

**Comment by luisjakon** [comment]
Well, that was easy. Thank you! : )
