### ISSUE TITLE
[Feature Request]: Have cursor jump to selectable variables in the scope window

### ISSUE THREAD

**Issue by RonanMacF** [rcarriga/nvim-dap-ui#25]
In the scope window the only 'actionable' items are those that are expandable. It would be a small efficiency improvement if pressing 'j' or 'k' jumped to lines which are actionable. At the moment relative jumps is probably the fastest way but I feel like this would make variable inspection faster

An example in the picture would be if I press `j`, it would jump from line 7 to line 23. Everything in between is already visible and cant be expanded anymore. 

I'm not sure if something like this is feasible as it would stop other things being possible e.g. yanking variables or something like that, but maybe this could be toggleable. Just an idea anyways.

Alternatively if could be a keymapping where <C-j> jumps to next actionable etc.

![Screenshot 2021-06-11 at 13 4206](https://user-images.githubusercontent.com/25930627/121687935-d1f2a500-caba-11eb-9560-e089824967c0.png)

**Comment by rcarriga** [comment]
I don't think this is functionality I'd want to place in to the plugin, but this is something that could be easily achieved with a simple search mapping. 
Add this to `~/.config/nvim/ftplugin/dapui_scopes.vim` and you can do just what you need with J/K (I'd imagine you would want to keep j/k as normal in case of yanking text or something.
```vim
nnoremap <buffer><silent> J /⯈\\|⯆<CR>:nohlsearch<CR>
nnoremap <buffer><silent> K ?⯈\\|⯆<CR>:nohlsearch<CR>
```

**Comment by RonanMacF** [comment]
True, this is trivial enough to expect the user to be able to do. Closing, thanks
