### ISSUE TITLE
Text is inserted when calling `eval` after editting value 

### ISSUE THREAD

**Issue by jamestansx** [rcarriga/nvim-dap-ui#250]
Perhaps the title is not clear enough, I have also provided a video demo. 

When calling `eval` and edit the variable inside the floating window (with key `e`), calling `eval` the second time will cause weird behavior where the same word under cursor will be inserted and will change to insert mode.

https://user-images.githubusercontent.com/45304579/225637456-bbb5494a-4cd1-415f-905b-ef6cc8ec0280.mov

**Comment by Nosterx** [comment]
Same here. 
[Kazam_screencast_00009.webm](https://user-images.githubusercontent.com/4470993/226080624-97d6d971-fae8-41ef-a6a4-0e46642992c7.webm)

**Comment by rcarriga** [comment]
Should be fixed in latest master :smile: It was a bad assumption that the current buffer was the buffer being rendered

**Comment by jamestansx** [comment]
Tested, it's all good now! Thanks for the fix! 😃
