### ISSUE TITLE
hi, how can I solve this icons issue?

### ISSUE THREAD

**Issue by guodongq** [rcarriga/nvim-dap-ui#257]
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/50981063/229563032-b75369b2-24f4-40e2-9bf9-97b041092ed3.png">

my neovim config as following:

https://github.com/guodongq/dotfiles/blob/master/nvim/lua/plugins/dap.lua
https://github.com/guodongq/dotfiles/blob/master/nvim/lua/config/plugins.lua#L347-L380

**Comment by guodongq** [comment]
thanks, the problem has been resolved, the root cause is the configuration on the terminal as follows

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/50981063/229640256-6067c292-f26d-4028-a9be-7944124ba422.png">

the terminal should be chosen a font which can support these icons

**Comment by EpsilonKu** [comment]
Cool, will be good to close issue

**Comment by guodongq** [comment]
the issues resolved, close the isue directly
