### ISSUE TITLE
When using watch element and cppdbg, error occurs.

### ISSUE THREAD

**Issue by pittcat** [rcarriga/nvim-dap-ui#26]
Error info:
```
Error executing vim.schedule lua callback: .../.vim/plugged/nvim-dap-ui/lua/dapui/elements/watches.lua:19: attempt to index field 'error' (a nil value)
```
The error message is similar to the previous one.
https://github.com/rcarriga/nvim-dap-ui/issues/22#issuecomment-859553394

**Comment by pittcat** [comment]
https://asciinema.org/a/xLwxoaUcRseTw2i7ff46oAjBh

**Comment by rcarriga** [comment]
Hmm looks like it breaks the specification. Could you paste the dap log with level set to debug please?

**Comment by pittcat** [comment]
Here is the log.
https://gist.github.com/pittcat/36540c4b8097aac5a390aa75ef2a1f8f

**Comment by rcarriga** [comment]
Perfect thank you, please try with latest commit

**Comment by pittcat** [comment]
The patch fixed the bug. Thank you.
