### ISSUE TITLE
Can't enter insert mode after close session.

### ISSUE THREAD

**Issue by YuCao16** [rcarriga/nvim-dap-ui#262]
Hello,

If I open `dapui` window and then close it, I'm not able to enter insert mode (It will back to normal mode automatically). This happens after I upgrade to `neovim` 0.9.0, and I tested with the same config on `neovim` 0.8.3, everything is fine. Is this plugin not yet available for version 0.9.0?

**Comment by YuCao16** [comment]
Actually, the nightly `neovim` works fine as well... So I upgrade to `NVIM v0.10.0-dev-53+g5ccec143d`.

**Comment by edward-s** [comment]
can this be reopened? i have the same issue, but i want to stick to stable neovim 0.9

**Comment by edward-s** [comment]
i found out that this has nothing to do with nvim-dap-ui, most likely it's nvim-dap issue
anyways, i downgraded to 0.83 for now

**Comment by edward-s** [comment]
this issue is apparently going to be fixed in the upcoming nvim 0.9.1
https://github.com/neovim/neovim/issues/22924

**Comment by mikeborodin** [comment]
can confirm, upgrading to dev version ( ` brew install --HEAD neovim` ) helps

**Comment by leoentersthevoid** [comment]
Upgrading to dev (NVIM v0.10.0-dev-361+ge3e6fadfd) solved it on my end as well.

**Comment by rcarriga** [comment]
Closing as this is not a nvim-dap-ui issue

**Comment by ajayd-san** [comment]
This started to happen again...I'm on `v0.11.0-dev` (nightly).

Even after closing dapui I cannot go back to editing my code since normal mode operations are intercepted by dap (or dap-ui, I'm not sure which).
