### ISSUE TITLE
How to set breakpoint when unhandled exception occurs?

### ISSUE THREAD

**Issue by SamPosh** [rcarriga/nvim-dap-ui#263]
I'm using nvim-dap-ui and nvim-dap-python,When unhandled exception occurs ,all the dap ui windows are closed, I could not see what was the last error occurred.

In vscode if unhandled exception occurs then the breakpoint would hit at that line.

How to achieve the same thing in nvim-dap-ui?

**Comment by igorlfs** [comment]
Read :h dap.set_exception_breakpoints()
