### ISSUE TITLE
Evaluation happens twice with `dapui.eval` 

### ISSUE THREAD

**Issue by Ultimator14** [rcarriga/nvim-dap-ui#265]
I'm debugging a python program with debugpy.  
When evaluation an expression (using `dapui.eval`) that changes a value, the evaluation is done twice.  
This does not happen with the dap repl window.

Steps to reproduce:
1. Use this test program
```python
a = [1]
print(len(a))
print(len(a)) <-- insert breakpoint here
print(len(a))
```
2. Insert breakpoint at line 3
3. Run program, first print shows `[1]`
4. Execute `:lua require('dapui').eval("a.append(2)")` on breakpoint
5. Step next
6. `a` is now `[1,2,2]` instead of `[1,2]`

Note: Initially, I tried the built in expression (watches) element. But since all the expressions there are recomputed on refresh, the change would be executed all the time, too (which is probably not fixable). Instead, I created a separate keybinding for executing expressions without displaying them in the expressions window.

```lua
local function dapui_prompt_eval()
	local expr = vim.fn.input('Expression: ')
	if vim.fn.empty(expr) ~= 0 then return end
	eval(expr, {})
end

vim.keymap.set('n', '<leader>sE', dapui_prompt_eval, { desc = "Evaluate expression", silent = true })
```

**Comment by rcarriga** [comment]
Thanks for the report, this should now be working as expected :smile: As you said this is not fixable for `watches`. Really the hover shouldn't have any side effects but of course that's easier said than done for a debugger
