### ISSUE TITLE
[Feature Request]:Add support for watch expression record.

### ISSUE THREAD

**Issue by pittcat** [rcarriga/nvim-dap-ui#27]

**Comment by rcarriga** [comment]
Can you provide more info? Not sure what you're looking for

**Comment by pittcat** [comment]
When restarting the debug session, we don't need to input expression again in last debug session.

**Comment by rcarriga** [comment]
OK I've made the expressions persist across sessions, though it comes with a slight behaviour change. Watches will now always be evaluated in the current frame. This is how VS Code implements watches as well so I think it is the right choice between the two.
