### ISSUE TITLE
How to change focus for all float_element()'s by default?

### ISSUE THREAD

**Issue by Fabian-programmer** [rcarriga/nvim-dap-ui#273]
Hey,

I'm not sure if its intended or not, but when I start

`require("dapui").float_element()`

I can select following elements:

![grafik](https://user-images.githubusercontent.com/65787013/236212741-71a50c21-1aaf-4e9c-8918-b63b760a5a6d.png)

When I select repl or console it sets the focus inside the floating window.
For anything else the focus stays outside. Now my problem is, when I move my cursor the floating window disappears. Currently I have to actively click into the floating window to keep it and do my work in there.

In the documentation, there is an enter attribute:

`require('dapui').float_element('all elements', { enter = true })`

but it is only possible to use it for a specific element? I would like to have it for all elements. I tried `{}` and `''` as element argument but both didn't work.

Is there an option, I am missing? 

Thank you!

**Comment by rcarriga** [comment]
> but it is only possible to use it for a specific element? I would like to have it for all elements. I tried {} and '' as element argument but both didn't work.

I don't understand what you mean by have it for all elements instead of a specific one. Do you mean you want to open a window for each element?

**Comment by Fabian-programmer** [comment]
I would like to use the picker for the elements.

`require("dapui").float_element()`

But for each element, I pick, the same behavior.
Whereas the behavior is, that the cursor is set into the floating window of the element, when picked.

**Comment by Fabian-programmer** [comment]
I've found for myself a minimalistic solution :

[dapui/init.lua#L138](https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/init.lua#L138)
`+ args.enter = true`

if you @rcarriga want this line of code in your repo I can create a PR with a config parameter instead of true.

another option would be to add for each element float_defaults with enter = true;

[breakpoints.lua](https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/elements/breakpoints.lua)
```
function dapui.elements.breakpoints.float_defaults()
  return { enter = true }
end
```

or change the default behaviour in the window manager, if the keyval `settings.enter` is not available enter by default:
[windows/init.lua](https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/windows/init.lua)

but these 2 other options are tooo intrusive for this small change :)

**Comment by Fabian-programmer** [comment]
Nope, just the suggestions above, but was waiting for an answer. And forgot that this issue ticket even existed :)

**Comment by ciganandrea** [comment]
> but it is only possible to use it for a specific element? I would like to have it for all elements. I tried {} and '' as element argument but both didn't work.

@Fabian-programmer try `nil`

```lua
require('dapui').float_element(nil, {enter = true})
```

**Comment by Fabian-programmer** [comment]
This works perfectly thank you @ciganandrea !!
