### ISSUE TITLE
Array elements in Locals are not automatically updated

### ISSUE THREAD

**Issue by logeshg5** [rcarriga/nvim-dap-ui#29]
![image](https://user-images.githubusercontent.com/2236190/121800790-6c84ec80-cc51-11eb-8159-701df7dc4263.png)

Whenever I step over a line that changes the elements of an arrary, the values are not updated in the Locals sidebar. 

This is only for elements within an array. All other locals like a normal integers are updated automatically. 

Currently I have to close the drop down and open again to see the updates. 

I am debugging C++ on NVIM v0.5.0-dev+nightly.

**Comment by rcarriga** [comment]
Thanks for flagging, please try the latest commit

**Comment by logeshg5** [comment]
Yes it is fixed, Thanks!
