### ISSUE TITLE
Change the name of the debug adapter.

### ISSUE THREAD

**Issue by SiirRandall** [rcarriga/nvim-dap-ui#291]
I love the UI thank you for the hard work, and I'm not sure if this is the place to put this issue. If it isn't, I apologize. I looked all over the place and couldn't find an answer. when I debug my discord programs in the debug window I see this

```
[debug-adapter stdout] DBCFG INIT:  mongodb
Type 'dlv help' for list of commands.

[debug-adapter stdout] Settings updated

[debug-adapter stdout] Developer Mode:  true
```

Is there a way to change the name or disable the messages for debug-adapter ?

**Comment by rcarriga** [comment]
I'm afraid nvim-dap-ui and nvim-dap have no control of the text that is sent by the adapter. You could open an issue on the adapter's repo to see if they could allow changing it
