### ISSUE TITLE
Highlight clarification

### ISSUE THREAD

**Issue by zacmar** [rcarriga/nvim-dap-ui#3]
The screenshots in the readme look very appealing, however I am not able to reproduce them on my local setup. There are no discernible highlights out-of-the-box (see screenshot), and it is unclear how to configure them (if possible at all). The highlights in `dapui.highlights` don't seem to have any effect, or am I missing something? I am loading my colorscheme (`gruvbox-material`) prior to requiring `dapui`.
![2021-04-11-140924_1440x479_scrot](https://user-images.githubusercontent.com/32982619/114303756-f7216200-9acf-11eb-9690-c77b956ae6c0.png)

Highlighting is very important here imo, since the naturally narrow windows clutter up very quickly (I artificially widened the above screenshot for clarity):
![2021-04-11-141223_361x642_scrot](https://user-images.githubusercontent.com/32982619/114303754-f2f54480-9acf-11eb-8a2d-9eb5fd8b0c09.png)

What is the canonical way to set these highlights? Maybe it is even possible to simply link to tree-sitter groups, such that tree-sitter aware colorschemes can benefit from this without cost?

**Comment by rcarriga** [comment]
The highlight groups should definitely be having an effect, they don't rely on the colour scheme at all. I'm not really sure of the issue here so I'll have to just ask for more info... I'll start with:

1. Can you check the highlights are loaded by checking output of `:hi DapUIVariable`?
2. What's the output of `nvim --version`?
3. Does reloading your file (by running `:edit`) have any effect?

If you could provide a minimal init.vim to reproduce this, it would be much easier for to pin down the issue without needing to get you to report back.

By the way I think you might benefit by having wrapping disabled in the windows. I've set it as the default in the latest commit.

**Comment by zacmar** [comment]
`init_.lua`:
```lua
vim.cmd("let mapleader=','")
vim.cmd('packadd! nvim-dap')
vim.cmd('packadd! nvim-dap-ui')

vim.api.nvim_set_keymap("n", "<F2>", ":lua require'dap'.continue()<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<F3>", ":lua require'dap'.step_over()<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<F4>", ":lua require'dap'.step_into()<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<F5>", ":lua require'dap'.step_out()<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<leader>db", ":lua require'dap'.toggle_breakpoint()<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<leader>dB", ":lua require'dap'.set_breakpoint(vim.fn.input('Breakpoint condition: '))<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<leader>lp", ":lua require'dap'.set_breakpoint(nil, nil, vim.fn.input('Log point message: '))<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<leader>dr", ":lua require'dap'.repl.open()<CR>", { silent = true })
vim.api.nvim_set_keymap("n", "<leader>dl", ":lua require'dap'.repl.run_last()<CR>", { silent = true })

local dap = require('dap')
dap.adapters.python = {
    type = 'executable';
    command = 'python';
    args = { '-m', 'debugpy.adapter' };
}
dap.configurations.python = {
    {
        type = 'python';
        request = 'launch';
        name = "Launch file";
        program = "${file}";
        pythonPath = function()
            return 'python'
        end;
    },
}
require("dapui").setup()
```
`test.py`:
```
import numpy as np


def _main():
    a = np.array([[1, 2, 3]])
    A = a.T @ a
    print(A)


if __name__ == '__main__':
    _main()

```
`nvim -u init_.lua test.py`:
![2021-04-11-150324_1012x912_scrot](https://user-images.githubusercontent.com/32982619/114305134-2be4e780-9ad7-11eb-821d-893559c29b1e.png)

```
:hi DapUIVariable
DapUIVariable xxx links to Normal

```
```
$ nvim --version
NVIM v0.5.0-dev+1233-g82ac44d01
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/martin/.cache/paru/clone/neovim-nightly-git/src/build/config -I/home/martin/.cache/paru/clone/neovim-nightly-git/src/neovim-nightly-git/src -I/usr/include -I/home/martin/.cache/paru/clone/neovim-nightly-git/src/build/src/nvim/auto -I/home/martin/.cache/paru/clone/neovim-nightly-git/src/build/include
Compiled by martin

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

**Comment by zacmar** [comment]
Edit: Of course I forgot to `:set termguicolors` in the minimal init_.lua, with this it looks like this:
![2021-04-11-152858_420x635_scrot](https://user-images.githubusercontent.com/32982619/114306011-be3aba80-9ada-11eb-9855-94fd6653f181.png)
So I would have to investigate further why it doesnt work with my actual config.

**Comment by zacmar** [comment]
Highlights are cleared because of [this](https://github.com/sainnhe/gruvbox-material/blob/9ab5adde6cbe41af0f846d8f176261c83813cdca/colors/gruvbox-material.vim#L17) line in gruvbox-material. Not sure why this is called in my case, but it definitely is not a problem with this plugin.

**Comment by rcarriga** [comment]
Aha good to know :+1: Should be fine then as long as you source gruvbox first

**Comment by RonanMacF** [comment]
@zacmar did you find a solution for this?

I tried putting `colorscheme gruvbox`, `colorscheme moonlight` and `colorscheme sonokai` at the top of my init.vim in different tests and still nothing. I also tried putting the following at the bottom of my init.vim but that didn't help either.
```

  hi default link DapUIVariable Normal
  hi default DapUIScope guifg=#00F1F5
  hi default DapUIType guifg=#D484FF
  hi default DapUIDecoration guifg=#00F1F5
  hi default DapUIThread guifg=#A9FF68
  hi default DapUIStoppedThread guifg=#00f1f5
  hi default link DapUIFrameName Normal
  hi default DapUISource guifg=#D484FF
  hi default DapUILineNumber guifg=#00f1f5
  hi default DapUIFloatBorder guifg=#00F1F5
  hi default DapUIWatchesHeader guifg=#00F1F5
  hi default DapUIWatchesEmpty guifg=#F70067
  hi default DapUIWatchesValue guifg=#A9FF68
  hi default DapUIWatchesError guifg=#F70067
  hi default DapUIWatchesFrame guifg=#D484FF
  hi default DapUIBreakpointsPath guifg=#00F1F5
  hi default DapUIBreakpointsInfo guifg=#A9FF68
  hi default DapUIBreakpointsCurrentLine guifg=#A9FF68 gui=bold
  hi default link DapUIBreakpointsLine DapUILineNumber
```

**Comment by RonanMacF** [comment]
not ideal but I suppose the following will do the job
```
augroup loadColors
  autocmd BufEnter * :call SetColours()
augroup END

function! SetColours()
  hi default link DapUIVariable Normal
  hi default DapUIScope guifg=#00F1F5
  hi default DapUIType guifg=#D484FF
  hi default DapUIDecoration guifg=#00F1F5
  hi default DapUIThread guifg=#A9FF68
  hi default DapUIStoppedThread guifg=#00f1f5
  hi default link DapUIFrameName Normal
  hi default DapUISource guifg=#D484FF
  hi default DapUILineNumber guifg=#00f1f5
  hi default DapUIFloatBorder guifg=#00F1F5
  hi default DapUIWatchesHeader guifg=#00F1F5
  hi default DapUIWatchesEmpty guifg=#F70067
  hi default DapUIWatchesValue guifg=#A9FF68
  hi default DapUIWatchesError guifg=#F70067
  hi default DapUIWatchesFrame guifg=#D484FF
  hi default DapUIBreakpointsPath guifg=#00F1F5
  hi default DapUIBreakpointsInfo guifg=#A9FF68
  hi default DapUIBreakpointsCurrentLine guifg=#A9FF68 gui=bold
  hi default link DapUIBreakpointsLine DapUILineNumber
endfunction
```

**Comment by zacmar** [comment]
@RonanMacF Although I don't quite understand what is exactly going on, (as @rcarriga correctly noted, one would think that sourcing gruvbox first should solve the issue, but it doesn't) I just set `vim.g.gruvbox_material_better_performance = 1` in my `init.lua`, as this skips the line that clears the highlights.
