### ISSUE TITLE
The buttons for continue, step over, step into, stop, etc. are hidden behind [dap-repl]

### ISSUE THREAD

**Issue by ishaan-kapoor** [rcarriga/nvim-dap-ui#302]
I have just installed nvim-dap and nvim-dap-ui and the tutorials on youtube and the readme of this repo show the vscode like buttons for continue,step into, etc. but in my setup the is no such button.
If i switch panes too fast using ctrl+j (vim-tmux-navigator) in neovim, I can see flashes of those buttons behind the repl heading.

P.S. sorry for bad English, its not my native tongue.

**Comment by massimiliano-della-rovere** [comment]
+1 same here

here is my configuration: https://github.com/massimiliano-della-rovere/nvim/blob/main/lua/plugins/debugging.lua
font: Hack Nerd Font
terminal: KDE's Konsole

**Comment by jiangyinzuo** [comment]
Hello @ishaan-kapoor ,

If you are using [lualine.nvim](https://github.com/nvim-lualine/lualine.nvim), remember to setup `disabled_filetypes` for `dap-repl` filetype. nvim-dap-ui puts the buttons in the winbar so you will see the flash if you have not disabled winbar for `dap-repl` filetype in lualine. 

The following is my configuration that fixes this problem.
```lua
	require("lualine").setup({
		options = {
			icons_enabled = true,
			-- theme = 'solarized',
			component_separators = { left = "", right = "" },
			-- leave them blank, or lualine will kill intro.
			-- https://github.com/nvim-lualine/lualine.nvim/issues/259#issuecomment-1890485361
			section_separators = { left = "", right = "" },
			disabled_filetypes = {
				statusline = {
					"dap-repl",
					"dapui_breakpoints",
					"dapui_console",
					"dapui_scopes",
					"dapui_watches",
					"dapui_stacks",
				},
				winbar = {
					"dap-repl",
					"dapui_breakpoints",
					"dapui_console",
					"dapui_scopes",
					"dapui_watches",
					"dapui_stacks",
				},
			},

```

**Comment by ishaan-kapoor** [comment]
Thanks a lot, that fixed it.
