### ISSUE TITLE
Highlighting the current frame does not work

### ISSUE THREAD

**Issue by przepompownia** [rcarriga/nvim-dap-ui#303]
![image](https://github.com/rcarriga/nvim-dap-ui/assets/11404453/64dc511e-752c-4ad6-9e36-e5320ba28ca7)

Currently I can't see which frame is current.

I found `DapUICurrentFrameName` highlight inside `frames.lua` but it doesn't seem to be applied. `:Inspect` on the current frame's line shows 

![image](https://github.com/rcarriga/nvim-dap-ui/assets/11404453/a6a51551-0b0c-447c-aa41-c79f4971d0b5)

**Comment by przepompownia** [comment]
https://github.com/rcarriga/nvim-dap-ui/blob/34160a7ce6072ef332f350ae1d4a6a501daf0159/lua/dapui/components/frames.lua#L34

I noticed that for PHP adapter for none of `frames` `frame.id == current_frame_id`. 

Please look into the example from https://github.com/przepompownia/nvim-dap-ui-current-frame-bug (`make start` should be enough).
![image](https://github.com/rcarriga/nvim-dap-ui/assets/11404453/9e1d8291-2f1a-4157-b163-b4d02ce7025b)

I'm not sure if the bug lies on nvim-dap-ui side.

**Comment by przepompownia** [comment]
I see that `.frames` from nvim-dap displays the current frame correctly
![image](https://github.com/rcarriga/nvim-dap-ui/assets/11404453/f9f8c88f-d63e-43db-95da-52cfa1df8719)
but after jumping to another frame using default `o` keymap on the stacks window the current frame is not displayed also there
![image](https://github.com/rcarriga/nvim-dap-ui/assets/11404453/e08b83ad-3457-4de8-9bf2-0f4937537dbf)
Moreover, jumping between frames by `require('dap').up()` also returns then an error:
![image](https://github.com/rcarriga/nvim-dap-ui/assets/11404453/0ca9fe13-5ed0-4c56-889d-b46d281d6cf8)

**Comment by przepompownia** [comment]
I noticed that using `frames` directly from `dap.session` 
```diff
diff --git a/lua/dapui/components/frames.lua b/lua/dapui/components/frames.lua
index 7d1c87c..afbd653 100644
--- a/lua/dapui/components/frames.lua
+++ b/lua/dapui/components/frames.lua
@@ -19,6 +19,7 @@ return function(client, send_ready)
         return
       end
       local frames = response.stackFrames
+      frames = require'dap'.session().threads[thread_id].frames
 
       if not show_subtle then
         frames = vim.tbl_filter(function(frame)
```
simply works in this example:
![image](https://github.com/rcarriga/nvim-dap-ui/assets/11404453/4f25366f-3508-4472-9330-8a1ca04c00e0)

**Comment by rcarriga** [comment]
Thanks for the fix, I added a few extra changes and pushed to master

**Comment by przepompownia** [comment]
Thank you too. I took a look at how you made the access to frames without direct `require`ing `dap.session` in lua/dapui/components/frames.lua. It works for me so we have close this issue.

**Comment by przepompownia** [comment]
...althoug I get 
```
   Warn  06:24:06 PM notify.warn nvim-dap-ui Rendering failed: ...k/bundle/opt/nvim-dap-ui/lua/dapui/components/frames.lua:21: attempt to index a nil value
stack traceback:
	...nfig/nvim/pack/bundle/opt/nvim-dap-ui/lua/dapui/util.lua:26: in function '__index'
	...k/bundle/opt/nvim-dap-ui/lua/dapui/components/frames.lua:21: in function 'render'
	.../bundle/opt/nvim-dap-ui/lua/dapui/components/threads.lua:45: in function 'render_thread'
	.../bundle/opt/nvim-dap-ui/lua/dapui/components/threads.lua:73: in function 'render'
	...ack/bundle/opt/nvim-dap-ui/lua/dapui/elements/stacks.lua:27: in function 'render'
	...ack/bundle/opt/nvim-dap-ui/lua/dapui/elements/stacks.lua:19: in function <...ack/bundle/opt/nvim-dap-ui/lua/dapui/elements/stacks.lua:18>
	[C]: in function 'xpcall'
	...nfig/nvim/pack/bundle/opt/nvim-dap-ui/lua/dapui/util.lua:25: in function <...nfig/nvim/pack/bundle/opt/nvim-dap-ui/lua/dapui/util.lua:21>
```

after exiting if `continue` does not meet any breakpoint.

**Comment by mikehaertl** [comment]
Commit a62e86b124a94ad1f34a3f936ea146d00aa096d1 related to this issue introduced a new error for me. See #321

**Comment by mikehaertl** [comment]
> No thread 1
> No thread 7

**Comment by przepompownia** [comment]
@mikehaertl thanks for pointing out the place. Do you have a working frames view after this change?

**Comment by mikehaertl** [comment]
TBH I'm not sure what frames are. I see threads, though. Here's what a session looks like (Java):

![image](https://github.com/rcarriga/nvim-dap-ui/assets/675062/7227f052-ce0a-4f89-9c2f-e23ca3368808)

**Comment by przepompownia** [comment]
@mikehaertl you have visible frames on the screenshot. The widget hierarchy is DAP Stacks -> threads -> frames (@rcarriga please correct me if I'm wrong).
