### ISSUE TITLE
<backspace> can't delete character in watch window.

### ISSUE THREAD

**Issue by pittcat** [rcarriga/nvim-dap-ui#31]
This problem may be similar to the one I encountered in nvim-dap repl.
https://github.com/mfussenegger/nvim-dap/issues/119

**Comment by rcarriga** [comment]
This is a problem that with the neovim `prompt` buftype as can be seen at the end of that issue. Unfortunately I can't do anything to work around it. It seems to only be tracked in this issue but there has not been much activity on it https://github.com/neovim/neovim/issues/14116

**Comment by pittcat** [comment]
This solution will make backspace behave like esc when there is no character to delete, and this is not the same behavior as inside nvim-dap repl.

**Comment by pittcat** [comment]
Maybe you can follow the workaround. https://github.com/neovim/neovim/issues/14116#issuecomment-977555102
