### ISSUE TITLE
The display of array elements in the watch window is not the same as in nvim-dap repl.

### ISSUE THREAD

**Issue by pittcat** [rcarriga/nvim-dap-ui#32]
You can check problem by the url.
https://asciinema.org/a/bPbXj3FHo8efSwGphQeLAuTOL

**Comment by rcarriga** [comment]
Right now the watched expressions are pretty simple. I'm working on a refactor to allow for more complex watch expressions and hover expressions. Will update once I have something working well!

**Comment by rcarriga** [comment]
#35 has brought a lot of code changes which allowed for the hover and watch elements to have expansion capabilities exactly like the variables element. Please try with the latest commit!

**Comment by pittcat** [comment]
Thanks for your work.
