### ISSUE TITLE
Keep UI open after debug session has terminated

### ISSUE THREAD

**Issue by brucejxz** [rcarriga/nvim-dap-ui#328]
When a debug session completes successfully, the UI elements get closed automatically. It would be nice if there were an option to keep them around for further inspection as necessary.

**Comment by igorlfs** [comment]
You probably have something like
```
        dap.listeners.before.event_terminated.dapui_config = function() dapui.close() end
        dap.listeners.before.event_exited.dapui_config = function() dapui.close() end
```
In your config, which is causing this behavior. OOTB dapui isn't opened when a session start nor closed when it ends.
