### ISSUE TITLE
Insert mode in repl window is not exited after debugging ends

### ISSUE THREAD

**Issue by brymko** [rcarriga/nvim-dap-ui#33]
The moment debugging stops all windows automatically close. If we are currently in insert mode in the REPL window (i.e step through the entire program (NOT IF .exit is executed)) we are thrown into insert mode in the code window.
Now the real problem is the fact that the stuff you accidentally inserted isn't undoable.
Don't know if this is a bug by neovim (im on v0.5.0-dev+1423-ge2d3ad7bc)
However i've managed to fix this by manually going into normal mode after the window closes. Inserting this
```lua
function M.on_close()
    local key = vim.api.nvim_replace_termcodes("<Esc>", true, false, true)
    vim.api.nvim_feedkeys(key, 'n', true)
end
```
into https://github.com/rcarriga/nvim-dap-ui/blob/f7104d3275d8da1d85ec01cc8bd1a17dd3e5e57f/lua/dapui/elements/repl.lua#L34 here.

**Comment by rcarriga** [comment]
This is an annoying issue... Prompt buffers seem to be pretty funky right now. Thanks for flagging! 

Please try with the latest commit
