### ISSUE TITLE
Can't find a way to add a watchpoint 

### ISSUE THREAD

**Issue by Ilya-JBR** [rcarriga/nvim-dap-ui#331]
I need to add a watchpoint for variable for example 'ArgArray', I can do this using the repl (` watch *ArgArray@10), but I want a cleaner look using already opened window (watch widget).
Am I missing something?

**Comment by rcarriga** [comment]
You can add a watched value by just entering insert mode in the window, entering the variable name, and pressing enter. E.g. Full key sequence `iArgArray<CR>`

Or you can use the API, see `:help dapui.elements.watches`
