### ISSUE TITLE
Scopes element expands newlines ('\n') when debugging javascript code

### ISSUE THREAD

**Issue by hereGittyGitty** [rcarriga/nvim-dap-ui#339]
Hi @rcarriga,

Thx for the `nvim-dap-ui` plugin. I use and like it a lot.

# Problem summary
I do have a problem when I am debugging *javascript* code, using [vscode-js-debug](https://github.com/microsoft/vscode-js-debug). The *scopes* *element* expands `\n`, so each function in the scopes windows uses multiple lines. The scopes widget from [nvim-dap](https://github.com/mfussenegger/nvim-dap), does not have this problem. Please check my gif below

## Expected
I expect each variable/function in the scopes element to occupy one line (if `set nowrap`).

## Environment Information
- *OS*: `GNU/LINUX`
- *neovim* `:version` output:
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
``` 

- *nvim-dap* version (SHA1): `c43c2473ecb482a9d91f32c1d4c0098fffad3c7d`

- *nvim-dap-ui* version (SHA1): `9720eb5fa2f41988e8770f973cd11b76dd568a5d`

- *js-debug* version: `v1.87.0`
It was installed as described [here](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#javascript)

## My minimal init.vim
```vim
set nocompatible

set runtimepath+=/usr/local/src/neovim_dap_ui_minimal/nvim-dap
set runtimepath+=/usr/local/src/neovim_dap_ui_minimal/nvim-dap-ui
set runtimepath+=/usr/local/src/neovim_dap_ui_minimal/js-debug

lua << EOF
require("dap").adapters["pwa-node"] = {
  type = "server",
  host = "localhost",
  port = "${port}",
  executable = {
    command = "node",
    -- 💀 Make sure to update this path to point to your installation
    args = {"/usr/local/src/neovim_dap_ui_minimal/js-debug/src/dapDebugServer.js", "${port}"},
  }
}
require("dap").configurations.javascript = {
  {
    type = "pwa-node",
    request = "launch",
    name = "Launch file",
    program = "${file}",
    cwd = "${workspaceFolder}",
  },
}

local dapui = require("dapui")
dapui.setup({
  layouts = {
    {
      -- You can change the order of elements in the sidebar
      elements = {
        -- Provide as ID strings or tables with "id" and "size" keys
        { id = "scopes", size = 0.50 },
      },
      size = 40,
      position = "right", -- Can be "left", "right", "top", "bottom"
    }
  }
})

vim.api.nvim_create_user_command("DapSidebarScopesToggle", function()
  local widgets = require("dap.ui.widgets")
  local my_sidebar = widgets.sidebar(widgets.scopes)
  my_sidebar.toggle()
end, {})

vim.api.nvim_create_user_command("DapUiToggle", function()
  require("dapui").toggle()
end, {})
EOF

filetype plugin indent on
set nowrap
```

# minimal javascript source code i used
```js
/**
 * hello-world.js
 */
function capitalize(word) {
  return word.charAt(0).toUpperCase() + word.slice(1)
}

function hello(name) {
  return 'Hello ' + capitalize(name)
}

console.log(hello('john'))
console.log(hello('Sarah'))
console.log(hello('kai'))

/**
 * Output:
 *
 * Hello John
 * Hello Sarah
 * Hello Kai
 */
```

I started neovim like this:
```bash
VIMRUNTIME=/usr/local/src/neovim/runtime /usr/local/src/neovim/build/bin/nvim --clean -u /usr/local/src/neovim_dap_ui_minimal/minimal_init.vim hello_world.js
```

## gif showing my problem
![demo](https://github.com/rcarriga/nvim-dap-ui/assets/2407498/ccdd36b9-6295-4997-a597-b753a94c6e99)

Hope there is an easy fix for that.

Thx a lot and have a nice day. :)

**Comment by rcarriga** [comment]
This is the intended behaviour. The debug server expects that the values are displayed with multiple lines. You can limit the lines for each values with `max_value_lines` in the render config, see `:help dapui.Config.render`

**Comment by hereGittyGitty** [comment]
Nice, thx a lot :)

**Comment by asmodeus812** [comment]
@rcarriga there is a problem with that however, these `values` if we trim them to increase performance, we lose the ability to extract the complete value, if we keep max_lines big the performance is extremely bad, it gets to a slog, can we trim the value yet still be able to fetch it with a keymap or something like that in case we need the full value, but do not want to have it rendered. 

```js
Closure:
 ∩æ╝ __copyProps Function = (to, from, except, desc) => {
                            if (from && typeof from === "object" || typeof from === "function") {
                              for (let key of __getOwnPropNames(from))
                                if (!__hasOwnProp.call(to, key) && key !== except)
                                  __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
                            }
                            return to;
                          }
```
