### ISSUE TITLE
nvim-nio Error

### ISSUE THREAD

**Issue by ConsumedKing** [rcarriga/nvim-dap-ui#340]
I didn't have this error before, after the last update this shows up when trying to toggle the dap ui
I did install nvim-nio package
:version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

`E5108: Error executing lua: ...e/nvim/site/pack/packer/start/nvim-nio/lua/nio/tasks.lua:95: Async task failed without callback: The coroutine failed with this message:
.../packer/start/nvim-dap-ui/lua/dapui/components/hover.lua:28: attempt to index field 'session' (a nil value)
stack traceback:
        .../packer/start/nvim-dap-ui/lua/dapui/components/hover.lua: in function 'render'
        ...ck/packer/start/nvim-dap-ui/lua/dapui/elements/hover.lua:20: in function 'render'
        ...im/site/pack/packer/start/nvim-dap-ui/lua/dapui/init.lua:215: in function <...im/site/pack/packer/start/nvim-dap-ui/lua/dapui/init.lua:213>
stack traceback:
        [C]: in function 'error'
        ...e/nvim/site/pack/packer/start/nvim-nio/lua/nio/tasks.lua:95: in function 'close_task'
        ...e/nvim/site/pack/packer/start/nvim-nio/lua/nio/tasks.lua:117: in function 'step'
        ...e/nvim/site/pack/packer/start/nvim-nio/lua/nio/tasks.lua:145: in function 'run'
        ...im/site/pack/packer/start/nvim-dap-ui/lua/dapui/init.lua:213: in function 'update_render'
        ...im/site/pack/packer/start/nvim-dap-ui/lua/dapui/init.lua:360: in function 'toggle'
        /home/cyberboy/.config/nvim/lua/mustafa/remap.lua:9: in function </home/cyberboy/.config/nvim/lua/mustafa/remap.lua:9>`

**Comment by rcarriga** [comment]
Ah that would be because the error failed silently previously :sweat_smile: Should be fixed with the latest commit

**Comment by ConsumedKing** [comment]
Fantastic now it's working
