### ISSUE TITLE
Errors in nvim dap ui loading/closing without active DAP session

### ISSUE THREAD

**Issue by juanlopez4691** [rcarriga/nvim-dap-ui#343]
If I try to toggle (open or close) DAP UI (`lua require('dapui').toggle()`) without an existing DAP session, I get the following error:

```
E5108: Error executing lua ...nlopez/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:95: Async task failed without callback: The coroutine failed
 with this message:
...are/nvim/lazy/nvim-dap-ui/lua/dapui/components/hover.lua:28: attempt to index field 'session' (a nil value)
stack traceback:
        ...are/nvim/lazy/nvim-dap-ui/lua/dapui/components/hover.lua: in function 'render'
        ...share/nvim/lazy/nvim-dap-ui/lua/dapui/elements/hover.lua:20: in function 'render'
        ...ez/.local/share/nvim/lazy/nvim-dap-ui/lua/dapui/init.lua:215: in function <...ez/.local/share/nvim/lazy/nvim-dap-ui/lua/dapui/init.lua:2
13>
stack traceback:
        [C]: in function 'error'
        ...nlopez/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:95: in function 'close_task'
        ...nlopez/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:117: in function 'step'
        ...nlopez/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:145: in function 'run'
        ...ez/.local/share/nvim/lazy/nvim-dap-ui/lua/dapui/init.lua:213: in function 'update_render'
        ...ez/.local/share/nvim/lazy/nvim-dap-ui/lua/dapui/init.lua:360: in function 'toggle'
        [string ":lua"]:1: in main chunk
```

Seems the same as [previously closed isssue #341](https://github.com/rcarriga/nvim-dap-ui/issues/341).

**Comment by ABeeinSpace** [comment]
I get the same error

**Comment by smile-kindred** [comment]
+1

**Comment by rcarriga** [comment]
Can you confirm that you are on the latest commit? [The line of code](https://github.com/rcarriga/nvim-dap-ui/blob/edfa93f60b189e5952c016eee262d0685d838450/lua/dapui/components/hover.lua#L28) that is erroring is pretty simple so I'm not sure how it could be doing that with the latest fix

**Comment by ABeeinSpace** [comment]
I am not, lazy.nvim (or AstroNvim, not sure which) still has me on commit f7d75cc. I'll wait until I get the fix. Thanks!

**Comment by smile-kindred** [comment]
sorry，astronvim used the wrong version

**Comment by jharlow** [comment]
@smile-kindred Could you explain what your solution was? I have the same issue with my AstroNvim setup and think I must be overlooking something obvious! I'd really appreciate it if you could point me in the right direction!

**Comment by PatMulligan** [comment]
@jharlow hey, after a bit of peaking around from the above, I wound up going to `~/.local/share/nvim/lazy/nvim-dap-ui` (at least on linux) and did a git status to reveal that I too was on commit [f7d75cc](https://github.com/rcarriga/nvim-dap-ui/commit/f7d75cca202b52a60c520ec7b1ec3414d6e77b0f) which is tagged as v4.0.0. 
I did a `git checkout master` to get to commit [edfa93f](https://github.com/rcarriga/nvim-dap-ui/commit/edfa93f60b189e5952c016eee262d0685d838450).

**Comment by Uzaaft** [comment]
Would it possible to get a release containing this? Astronvim is pinned to the v4 releases, so a release would solve this issue for most people using astro.
