### ISSUE TITLE
Dap ui is missing buttons, icons controls, for Continue, step over, step into, etc

### ISSUE THREAD

**Issue by AddictArts** [rcarriga/nvim-dap-ui#345]
I can bring up the ui, but it is missing the interaction for continue, step over, step into, etc.

Here is my config using lazy

```
{
  "rcarriga/nvim-dap-ui",
  dependencies = { "mfussenegger/nvim-dap", "nvim-neotest/nvim-nio" },
}

```

**Comment by AddictArts** [comment]
For anyone else in the future installing the codicons did the trick.

```
npm i -g @vscode/codicons
```

**Comment by shmerl** [comment]
You can configure them with Unicode symbols without the need for custom fonts.
