### ISSUE TITLE
backspace can't work.

### ISSUE THREAD

**Issue by cogig** [rcarriga/nvim-dap-ui#36]
Backspace can't delele character in watch window.
https://github.com/rcarriga/nvim-dap-ui/issues/31
https://github.com/mfussenegger/nvim-dap/issues/119
https://github.com/neovim/neovim/issues/14116
I think nvim-dap-ui should add some code for temporary workarround just like nvim-dap.
https://github.com/mfussenegger/nvim-dap/pull/120
https://github.com/mfussenegger/nvim-dap/pull/123

**Comment by rcarriga** [comment]
OK I've put in a similar workaround, I didn't think about a custom backspace mapping which works nicely. Please try latest commit

**Comment by rcarriga** [comment]
Closing due to no response and issue has been fixed
