### ISSUE TITLE
Specific keymaps that will work only while dap-ui session is active

### ISSUE THREAD

**Issue by elderkeltir** [rcarriga/nvim-dap-ui#368]
Cheers!

Firstly I wanted to express my gratitude towards this project, it rocks!
Then I'd like to ask, maybe there is some way that I'm not aware of, to set keymaps that will work only while I'm debugging?
I really want single key assigned for actions like: next, continue, step, finish, eval. But I need them only while I'm debugging.
There is ability to set such custom keymaps for file type, but this will not work, because filetype is the same as always(for main wondow with source code).
So maybe there is a way to resolve my issue?

Thanks in advance!

**Comment by rcarriga** [comment]
The simplest way to do this would be by just checking if there is an active session to decide what to do for your keymap. Something like this would work
```lua
local dap = require("dap")

local function dap_mapping(active, inactive)
  return function(...)
    if dap.session() then
      active(...)
    else
      inactive(...)
    end
  end
end

vim.keymap.set("n", "lhs", dap_mapping(function()
  print("Session is active")
end, function()
  print("No session is active")
end)
)
```

You can also use the dap events to set keymaps and unset them when debugging starts/stops
