### ISSUE TITLE
nvim displays error after today update

### ISSUE THREAD

**Issue by JoseConseco** [rcarriga/nvim-dap-ui#37]
I get this in error log:
![image](https://user-images.githubusercontent.com/13521338/126875010-1588d626-ea4e-4793-a1e7-d450deac3817.png)

Removing nvim-dap-if fixes the issue. All other plugins seems to work ok

**Comment by JoseConseco** [comment]
After bit of tesling the d7fefe656257f10b03aad0e7413e1b58f452781f works ok.  Thus the next commit broke  something

**Comment by Angshuman95** [comment]
I set up `dap-ui` like the following and I had the error
`require('dapui').setup()`

Doing this temporarily seems to solve the issue
`require('dapui').setup({})`

**Comment by rcarriga** [comment]
Thanks for the report! Please try with the latest commit

**Comment by JoseConseco** [comment]
thx. The issue is gone now.
