### ISSUE TITLE
[Question] Hide/change order of variable types

### ISSUE THREAD

**Issue by Maritsu** [rcarriga/nvim-dap-ui#372]
Is it possible to hide/change the order of variable types in the `scopes` view? For example, in C++ with `codelldb` server, `static` variables tend to take up a lot of space and if I have any global variables I can't see them without scrolling through the whole scopes view.

**Comment by rcarriga** [comment]
I've added a sorting function option for rendering variables, you can have a look at the DAP spec for what information is available on the variable objects

**Comment by Maritsu** [comment]
Thank you very much, I'll check it out!
