### ISSUE TITLE
Switch tray state by require("dapui").toggle("tray") will break the layout of the window.

### ISSUE THREAD

**Issue by pittcat** [rcarriga/nvim-dap-ui#38]
The init window layout:
![dap-ui](https://user-images.githubusercontent.com/22888402/126917787-4abce347-5a58-4923-933f-c3bc409b37de.png)

**Comment by pittcat** [comment]
The layout after toggle("tray"):
![dap-ui-toggle](https://user-images.githubusercontent.com/22888402/126917815-cf200bab-47d0-4095-8e00-4c453aa3da66.png)

**Comment by rcarriga** [comment]
This should be working as expected now!
