### ISSUE TITLE
Watches not updated

### ISSUE THREAD

**Issue by erietz** [rcarriga/nvim-dap-ui#39]
Variables added to a watch are not automatically updated in the watch window. I have to go back to the watch window and re-add the variable for it to update.

Here is my configuration
```lua
require("dapui").setup()
require('dap-python').setup('~/miniconda3/envs/debugpy/bin/python')
```

If I add a watch variable to `tmp` in the following code, tmp stays at 0 throughout the loop rather than being incremented (see screenshot below).

```python
for i in range(10):
    tmp = i
    print(tmp)
```

![2021-07-26-123359_1904x1292_scrot](https://user-images.githubusercontent.com/11425271/127034265-890ad82f-e78d-437c-b762-ec3c0cddb604.png)

**Comment by rcarriga** [comment]
Ah thanks for the report! Please try latest commit, should be working fine now
