### ISSUE TITLE
js-debug-adapter logs appear in repl window instead of console window

### ISSUE THREAD

**Issue by nowaylifer** [rcarriga/nvim-dap-ui#396]

**Comment by ArthurKamalov** [comment]
It seems to be the same for dap-go
![Peek 2024-09-02 18-00](https://github.com/user-attachments/assets/fdbe132f-8ec4-44d0-a176-253adbefc2ff)

**Comment by ArthurKamalov** [comment]
it seems that the nvim-dap-python works correctly and outputs to the console element, so it may be some configuration problem, but a wonder where.

**Comment by rcarriga** [comment]
This is a configuration issue with your adapter, nothing to do with nvim-dap-ui. In python you accomplish this with `console = "integratedTerminal"` in the configuration, no idea what it is for other adapters
