### ISSUE TITLE
Authentication plugin error on connection

### ISSUE THREAD

**Issue by GrimalDev** [rcarriga/nvim-dap-ui#402]
Hello,

I realize that this might be a problem with my config or my server setup. But I have been having this issue since an update for a while now (not that it could also be related to the upgrade to mysql 10 of my db). I can't open a connection...
DapUI seems to be responding an SQL authenticating error about an extension that isn't present on my part. But I have tried every solutions I could find online with no success...
Maybe someone will relay.

```
[DBUI]
   Error connecting to db immo: DB exec error: ERROR 2059 (HY000): Authentication
    plugin 'mysql_native_password' cannot be loaded: dlopen(/opt/homebrew/Cellar/
   mysql/9.0.1_2/lib/plugin/mysql_native_password.so, 0x0002): tried: '/opt/homeb
   rew/Cellar/mysql/9.0.1_2/lib/plugin/mysql_native_password.so' (no such file),
   '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/mysql/9.0.1_2/lib/pl
   ugin/mysql_native_password.so' (no such file), '/opt/homebrew/Cellar/mysql/9.0
   .1_2/lib/plugin/mysql_native_password.so' (no such file)
```

As you can see my packages are handled by homebrew. The error is logic, because the mysql_native_password plugin is in fact not present in the the folder. But why would it need it now?

Thank you for any help.

**Comment by rcarriga** [comment]
That says `DBUI` not `dapui`, unrelated to this plugin
