### ISSUE TITLE
`eval` window stays open

### ISSUE THREAD

**Issue by pierpo** [rcarriga/nvim-dap-ui#41]
Hi! First of all, congratulations on the amazing plugin!

I just tried out the `eval` feature. Having the variable value in a floating window is great, but I can't close it easily.
I need to focus it (by clicking, or triggering `eval` a second time) and `:q`.

One would expect the window to close on cursor movement, except if it has been focused!

(also, the window is always on the top left corner of the screen... one would expect it to be under the cursor, but it's not a big deal)

What do you think?

Thank you for your fantastic work.

**Comment by rcarriga** [comment]
Thanks for the feedback :grin: OK so two points here, the window not closing is a side effect of a performance optimisation, please try with the latest commit!

The window opening in the corner is odd, can you give more info? How are you opening (via manually typing command or mapping)? Current window layout? etc

**Comment by pierpo** [comment]
Thank you for the extremely fast answer and solution!

It works perfectly. I understand your concern, I see on your commit that you had to add an event on all cursor movements. Maybe as an optimization this could be added only once the window is open, and be removed right after?

___

About the window layout, I don't really know what to add :sweat_smile: 

I type `:lua require('dapui').eval()`, and I get this out of the box:

![Screenshot from 2021-07-28 14-22-17](https://user-images.githubusercontent.com/6313316/127321516-726e2a27-b0c7-492d-932d-55fedb1fa335.png)

I did not provide any custom configuration or anything. Could it be a conflict with another plugin?

As I said, don't bother too much with this, it's really minor. If you don't reproduce, you could wait for other people to report to gather more info :wink:

**Comment by rcarriga** [comment]
Ah simple fix, it was just the cursor position being reported as the position in the command line. Should be fixed now. 

> It works perfectly. I understand your concern, I see on your commit that you had to add an event on all cursor movements. Maybe as an optimization this could be added only once the window is open, and be removed right after?

Don't worry the autocmd is already only run when the window is open, and the `CursorMoved` check is only fired once, previously it was fired continuously when open

**Comment by pierpo** [comment]
Fantastic, everything works perfectly now!

Thank you so much! Keep up the great work, you're making the neovim ecosystem even better :blush:
