### ISSUE TITLE
Create keymap to close floating window

### ISSUE THREAD

**Issue by luathn** [rcarriga/nvim-dap-ui#43]
First, I wanna thank you for the awesome plugin.
![Screenshot_20210801_205517](https://user-images.githubusercontent.com/20609495/127773757-c413bbaf-0b22-40e1-bec2-3dddff9cfe14.png)
As you can see in my screenshot, when my cursor is in a floating window, I must type `:q` to quit. When I use native LSP, they added keymap `q` to close the floating window more natural. 
I can add mapping to vimrc like this:
```
autocmd FileType dapui_hover nnoremap <buffer> <silent> a :bdelete<cr>
```
But I think set buffer keymap in plugin's Float window is better.
Hope I can add that keymap to your plugin and it will be configurable:
```
  mappings = {
    close_floating = {"<Esc>", "q"},
  }
```
If you agree, I will create PR for this. Thank you!

**Comment by rcarriga** [comment]
Thanks for the great feedback, glad you're enjoying it!

 I've gone a slightly different route for the config because the mappings right now are window agnostic while this would not be. Instead I've added a separate mappings field for the floating window. Please try with the latest commit

**Comment by luathn** [comment]
@rcarriga Nice. It is like my implement in my pc now.
