### ISSUE TITLE
I want to create custom mappings in the dapui elements

### ISSUE THREAD

**Issue by amenonsen** [rcarriga/nvim-dap-ui#45]
I'd like to create some custom buffer-local mappings inside the dapui elements, just for convenience (e.g., taking a hint from spice.vim, i'm mapping <leader>r to go to repl, <leader>w to go to watches, …). I am currently using the following patch just to see if the idea can be made to work, with

```lua
require('dapui').setup({
  custom_mappings = {
    { "n", "<leader>w", "<cmd>1wincmd w<CR>", { noremap = true } },
    { … },
  },
})
```

```diff
diff --git a/lua/dapui/config/init.lua b/lua/dapui/config/init.lua
index 1ed4ff0..7dd316a 100644
--- a/lua/dapui/config/init.lua
+++ b/lua/dapui/config/init.lua
@@ -61,6 +61,7 @@ local default_config = {
     },
   },
   windows = { indent = 1 },
+  custom_mappings = {},
 }

 local user_config = {}
@@ -91,6 +92,7 @@ function M.setup(config)
   local filled = vim.tbl_deep_extend("keep", config or {}, default_config)
   filled.mappings = fill_mappings(filled.mappings)
   filled.floating.mappings = fill_mappings(filled.floating.mappings)
+  filled.custom_mappings = filled.custom_mappings or {}
   filled.sidebar = fill_elements(filled.sidebar)
   filled.tray = fill_elements(filled.tray)
   user_config = filled
@@ -121,4 +123,8 @@ function M.windows()
   return user_config.windows
 end

+function M.custom_mappings()
+  return user_config.custom_mappings
+end
+
 return M
diff --git a/lua/dapui/render/state.lua b/lua/dapui/render/state.lua
index a3e36fc..6130342 100644
--- a/lua/dapui/render/state.lua
+++ b/lua/dapui/render/state.lua
@@ -170,6 +170,9 @@ function M.render_buffer(state, buffer)
     api.nvim_buf_set_option(buffer, "modifiable", false)
     api.nvim_buf_set_option(buffer, "buftype", "nofile")
   end
+  for _, t in pairs(config.custom_mappings()) do
+      api.nvim_buf_set_keymap(buffer, unpack(t))
+  end
   return true
 end
```

This does work for me, but it's fragile because it depends on the windows being laid out on screen in a certain way (the default, I didn't bother to change anything). If you're at all interested in the idea, do you have any advice on how to do it more nicely?

**Comment by rcarriga** [comment]
Each of the elements has a unique filetype so it seems like just using a `ftplugin` file or `FileType` autocommand should work just fine. Unless I'm missing something?

**Comment by amenonsen** [comment]
No, you're right. I started out with autocmd, then had some vague idea about adapting to changed layouts, and somehow ended up totally lost in the weeds. Sorry for the noise.

**Comment by rcarriga** [comment]
Hey no worries, we all need a rubber duck sometimes! :grin:
