### ISSUE TITLE
Is there a way to adjust the color scheme?

### ISSUE THREAD

**Issue by vivek-dg** [rcarriga/nvim-dap-ui#46]
<img width="1303" alt="Screen Shot 2021-08-14 at 1 25 34 PM" src="https://user-images.githubusercontent.com/3953809/129459226-7ef2775d-74ce-4765-a3e7-d4add0947267.png">

I see here that regardless of the original color scheme, the UI scheme is constant. Wondering if there is a good way to match the theme.

**Comment by rcarriga** [comment]
You just have to redefine the highlights from https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/config/highlights.lua. You can do so by using the same command without the `default` argument.

**Comment by vivek-dg** [comment]
Ok Thanks.
