### ISSUE TITLE
Don't clear REPL when closing UI

### ISSUE THREAD

**Issue by DanielPower** [rcarriga/nvim-dap-ui#48]
When UI is toggled on, the REPL becomes cleared. It would be preferable to have the REPL be persistent.

When opening the REPL using `:lua require("dap").repl.open()` the REPL does not clear. It only clears when opening using `:lua require("dapui").toggle()`

Edit: It looks like `:lua require("dap").repl.close()` is what clears the REPL. Using that function closes the split and clears the history. But just closing the split with `:q` does not clear the history, such that when re-opening the contents will still be there.

So perhaps I should report this to nvim-dap instead.

Edit 2: Turns out you can call `repl.close({ mode="toggle" })` to close the repl without clearing its contents. So this can be fixed within `nvim-dap-ui`. I'll put up a PR shortly in case this is something you'd be interested in accepting.

**Comment by rcarriga** [comment]
Hey that sounds great thank you! :grin:

**Comment by DanielPower** [comment]
Setting `mode="toggle"` does prevent the buffer from getting cleared on close. But looks like one of the other window management calls in dapui's open function causes the buffer to get cleared. I'll try to investigate and get a PR up as soon as I can. But I wouldn't expect it to be until next week, as I won't have the time this weekend.

**Comment by rcarriga** [comment]
Thanks for the update, the reason it was still being cleared was the buffer was being deleted. I've added a small change to stop this happening. Please try with the latest commit

**Comment by DanielPower** [comment]
That works perfectly, thank you very much! 😄 
Sorry for the empty promise on putting up a PR. I was in the middle of moving, so I didn't have any time for hobby coding.

**Comment by rcarriga** [comment]
Brilliant! No problem at all, thanks for reporting and investigating :smile:

**Comment by HudsonMC16** [comment]
Maybe this needs to be revisited? Please let me know if you're experiencing this also: my dap-repl does not close when the debugger closes, and even if I leave it open into another debugger session, the contents are not preserved. What is the intended behavior? That the dap-repl closes but the contents are kept for the next time it opens?

**Comment by rcarriga** [comment]
The REPL itself is the one from [nvim-dap](https://github.com/mfussenegger/nvim-dap), nvim-dap-ui just handles controlling the window. I believe it is intended that the text is cleared between runs of the REPL. I'm not sure if this is configurable, I suggest opening an issue on nvim-dap to see if you can preserve it :smile:

**Comment by HudsonMC16** [comment]
I'm actually not too attached to the contents of the repl; perhaps I misunderstood the point of this issue and the changes. I was just investigating why my repl wasn't closing when the debugger finished, and was poking around commits around the relevant bits of code in nvim-dap-ui. I'm getting a better understanding of this, I think, and maybe I should be doing the same for the [relevant bits of code from nvim-dap.](https://github.com/mfussenegger/nvim-dap/blob/55971c4f5cf83177a38bdec9de7bea6711c94880/lua/dap/ui.lua#L259) Thanks for your help!

**Comment by DanielPower** [comment]
@HudsonMC16 this issue is different from what you're asking about.

This issue was about the contents of the REPL buffer being cleared when you close the ui. It seems you're looking for an option to have the ui automatically close when you close the debugger session.

As far as I'm aware, that's not currently possible. There's an option to have the ui open when the debugger starts, but not the other way around. You could open a separate issue to request that feature.

**Comment by HudsonMC16** [comment]
Alright, I'm a bit confused then. Sorry to pollute an older issue with unrelated conversation, but once I know the intended behavior, I can start to figure out if what I'm seeing is a bug, config issue, or something I can (try to) fix with a PR. 

In my case, all of the ui elements do close when the debugger exits (except for the repl and terminal). This appears to be intended behavior based on all the window clean up code in this plugin. 

Again, sorry if I'm being dense.

**Comment by rcarriga** [comment]
By terminal I assume you mean the integratedTerminal. This is not supported by nvim-dap-ui and is only opened by nvim-dap. Closing that is up to the user, which someone has already automated see https://github.com/rcarriga/nvim-dap-ui/issues/49 and https://github.com/mfussenegger/nvim-dap/issues/278

How are you opening the REPL? If it's opened by the tray/sidebar then it should be closed automatically (if it's not then that sounds like a bug, please open an issue :smile:). If opening manually or using a floating window then you'll have to manually control the window using event listeners 
```lua
  dap.listeners.before.event_terminated["close_repl"] = function()
    dap.repl.close()
  end

  dap.listeners.before.event_exited["close_repl"] = function()
    dap.repl.close()
  end

```

**Comment by HudsonMC16** [comment]
It is the regular tray repl, but maybe I should add one point of clarification, as I think I'm not using the correct language. when I say the other UI elements are being closed, I mean the whole nine yards, i.e. the windows are being closed and the buffers deleted/unloaded. For the repl, the window is being closed but the buffer is persisting. This is what I mean when I say it's staying "open". This is the behavior offered by `require('dap').repl.toggle()` or `require('dap').repl.close({mode='toggle'})`. So seems like that's the intent, based on the code added to address this issue.

Sorry, I'm getting there! I'll just go ahead and add the hooks you mentioned above to delete the repl buffer in addition to closing the window. Thanks!
