### ISSUE TITLE
Option to have debugge's output's terminal auto closed on TermClose

### ISSUE THREAD

**Issue by oblitum** [rcarriga/nvim-dap-ui#49]
On nvim-dap-ui `.close()`, every dap-ui thing gets closed except for the debugee's output's terminal (I'm using `terminalKind = 'integrated'` on vscode's bashdb wrapper configured for nvim-dap).

![nvim-dap-ui](https://user-images.githubusercontent.com/1269815/130146808-419ad5ec-f66c-462f-879b-878e149a8209.gif)

I wished to have a nvim-dap-ui option for auto closing this dangling terminal on its `TermClose`.

Context: https://github.com/neovim/neovim/issues/14986#issuecomment-902705190

**Comment by oblitum** [comment]
An alternative (possibly tied to nvim-dap instead of the dap-ui?), is to have the debugge's terminals titled to be more distinguishable, so that I could put up an `autocmd` myself:

```vim
autocmd TermClose term://*dap-ui execute 'bdelete! ' . expand('<abuf>')
``` 

At the moment the terminal names are generic.

**Comment by rcarriga** [comment]
This problem is unrelated to nvim-dap-ui as the integrated terminals are completely handled by nvim-dap. There is no control of them from nvim-dap-ui unfortunately. You'll have to raise an issue in the nvim-dap repo

**Comment by oblitum** [comment]
Thanks. Done.
