### ISSUE TITLE
How to Jump to frame when a frame is selected from the stack

### ISSUE THREAD

**Issue by Badhi** [rcarriga/nvim-dap-ui#51]
`nvim-dap` supports jumping to the frame using the REPL as mentioned in the below comment
https://github.com/mfussenegger/nvim-dap/issues/6#issuecomment-632821997

Is it possible to do the same using the "Stack" Element?

I could see that the `open` mapping would move the cursor to the stack location, but it does not update the Scope variables and the cursor positions

**Comment by rcarriga** [comment]
OK please try the latest commit!

**Comment by Badhi** [comment]
Thanks works great
