### ISSUE TITLE
Removing last breakpoint doesn't update breakpoint widget

### ISSUE THREAD

**Issue by DanielPower** [rcarriga/nvim-dap-ui#52]
When adding or removing breakpoints, the breakpoint widget immediately updates. However, when there is only one breakpoint, removing it will not remove it from the breakpoint widget.

Attached is a video demonstrating the issue.
https://user-images.githubusercontent.com/12166320/131056673-55db2f3e-7961-4246-b858-4c7e45ba8347.mov

**Comment by rcarriga** [comment]
Thanks for the report! Please try with the latest commit :smile:
