### ISSUE TITLE
Highlight on side bar

### ISSUE THREAD

**Issue by alessiocelentano** [rcarriga/nvim-dap-ui#53]
I would like to apply Onedark.nvim highlight on the panel. I read [this issue](https://github.com/rcarriga/nvim-dap-ui/issues/3) but there isn't a real fix

![Screenshot_20210903_124655](https://user-images.githubusercontent.com/48618881/131993895-05127d9a-abeb-4c19-964b-c056d33124f3.png)

**Comment by rcarriga** [comment]
All you need to do is define the highlights to match the colour scheme. You can find them here https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/config/highlights.lua.

You could always open a PR to your colour scheme's repo so others can benefit from it too :smile:

**Comment by alessiocelentano** [comment]
Okay, thanks!
