### ISSUE TITLE
REPL next to sidebar

### ISSUE THREAD

**Issue by smackesey** [rcarriga/nvim-dap-ui#54]
I have a very wide screen and would prefer to have the REPL in a separate column next to the sidebar (with default contents). But it looks like right now that isn't possible-- you either use the tray or have to place the REPL inside a single-column sidebar.

Would you consider making it possible to use two columns?

**Comment by rcarriga** [comment]
Quite liked this idea! Try with the latest commit, you can now give `position = "left"` in the tray config to have it alongside the sidebar :grin:

**Comment by smackesey** [comment]
Thanks! Seems to be working for me.

I have another minor request. I virtually always enter the debug REPL when I start running the debugger. It would be nice to have the option to not just enter, but focus the REPL on debugger start. Here are three possible solutions:

- Add `focus_on_start` option.  Straightforward but expands configuration surface area, also introduces possibility of nonsensical config when `open_on_start` is false.
- Rename `enter_on_start` to `on_start` and allow it to take a string rather than a boolean. Possible values are `nil` (no open, no focus), `open` (open but no focus), and `focus` (open and focus)
- Emit a user autocommand event when the UI has been initialized that we can plug into with an autocommand.

**Comment by rcarriga** [comment]
Yeah I'm definitely in agreement on this, however I haven't implemented it because it adds more complexity to the plugin. I think the best solution is to remove the automatic open/close altogether and let users set it how they like. I'll think on it a bit more.

In the mean time, to work around this you can do the following after calling setup to stop the closing happening
```lua
  dap.listeners.before.event_terminated["dapui"] = nil
  dap.listeners.before.event_exited["dapui"] = nil
```
though this is not a supported mechanism, only a temporary workaround

**Comment by HudsonMC16** [comment]
Could a config flag be added to just open the whole ui in a separate tab, so it can stay there, untouched, until it's not needed anymore?

**Comment by rcarriga** [comment]
I think that would be even more reason to justify leaving the window opening to users rather than inside the plugin. There's no way I'll be able to account for all use cases so instead it's easier and cleaner to just expose the underlying controls and make no assumptions

**Comment by rcarriga** [comment]
I've disabled any automatic opening and closing of windows so you can define all the behaviour yourself now :smile:

**Comment by rcarriga** [comment]
Closing this as I believe there's no more for me to do here, feel free to re-open if there are issues
