### ISSUE TITLE
Highlight changed variables

### ISSUE THREAD

**Issue by elevin72** [rcarriga/nvim-dap-ui#55]
In VSCode debugger, when a variable's value changes, the whole thing gets highlighted, like in the picture below.
That would be a very nice enhancement to add imo.

![image](https://user-images.githubusercontent.com/11501767/132129756-5683b333-d959-47d3-a076-6ac495d8a0cf.png)

**Comment by rcarriga** [comment]
Please try the latest commit, you should see changed values being highlighted :smile:

**Comment by rcarriga** [comment]
Closing this but feel free to re-open if there's an issue
