### ISSUE TITLE
Close Mapping Does not Work for Floating REPL

### ISSUE THREAD

**Issue by knpwrs** [rcarriga/nvim-dap-ui#57]
I have the following configuration:

```lua
dapui.setup({
  floating = {
    mappings = {
      close = { '<C-d>' },
    },
  },
})
```

Pressing `<C-d>` is able to close floats which have elements such as `scopes`, but if the floating element is `repl`, it does not close when I press `<C-d>`, I instead have to press `<C-w>` and switch to another split.

**Comment by rcarriga** [comment]
Thanks for the report! Should be working in latest commit

**Comment by knpwrs** [comment]
Works great, thank you!
