### ISSUE TITLE
Windows should have fixed buffers

### ISSUE THREAD

**Issue by d-miketa** [rcarriga/nvim-dap-ui#58]
It's possible to highlight a UI window (e.g. `dap_stacks`) and change the buffer displayed within. Such behaviour is forbidden in, say, NvimTree. I think it makes sense here, too.

**Comment by rcarriga** [comment]
Sorry this took so long, it always just escaped my mind :sweat_smile: Should be working as requested now

**Comment by d-miketa** [comment]
No worries and thank you for looking into this, and indeed developing this plugin in the first place! :)

Unfortunately this fix didn’t work for me. Here is how to reproduce the issue:
- move into a DAP UI window
- attempt to change to another buffer
- the window is unchanged and the next window is highlighted
- the next window is changed to the desired buffer

But this next window can be a DAP UI window too, in which case the buffer still changes.

**Comment by rcarriga** [comment]
I don't seem to be able to reproduce the problem. The code is checking for a buffer's `buftype` to be empty before overriding it which should prevent dap-ui windows being replaced by others. Can you give a more concrete reproduction/recording of the issue?

**Comment by d-miketa** [comment]
You’re correct, the issue somehow went away on my machine too in the days since. All good - thank you! 😄
