### ISSUE TITLE
:lua require('dapui').close()<CR> wont close virtual text

### ISSUE THREAD

**Issue by JoseConseco** [rcarriga/nvim-dap-ui#59]
When I run dapui  close the virtual text stay visible. I have to restart  nvim to get rid of it: 
![image](https://user-images.githubusercontent.com/13521338/132958135-4bb43932-3079-43b1-bef0-6751b67d888f.png)

**Comment by rcarriga** [comment]
The virtual text is unrelated to nvim-dap-ui, you're looking for https://github.com/theHamsta/nvim-dap-virtual-text/ :smile:

**Comment by JoseConseco** [comment]
Sorry my bad .  Closing
