### ISSUE TITLE
Link the highlight groups to other elements instead of hardcoded gui only values?

### ISSUE THREAD

**Issue by lanza** [rcarriga/nvim-dap-ui#6]
I can't bind the custom highlights locally since you're overwriting them and don't use a GUI version of neovim, so the GUI layer shows up as nothing here. So any chance you can map these colors back to some default defined highlight groups and use your custom overrides locally?

**Comment by rcarriga** [comment]
They are defined using the `default` argument, so all you have to do is define them yourself without `default` e.g. `hi DapUIScope ctermfg=Green`
