### ISSUE TITLE
Weird behaviour when calling toggle() when tray set to not open on start

### ISSUE THREAD

**Issue by farbodsz** [rcarriga/nvim-dap-ui#60]
When I start a debugging session, the sidebar opens as expected. In my case I have set the tray to not open on start, so it does not appear with the sidebar:

```lua
dapui.setup({
  ...
  sidebar = {
    open_on_start = true,
    ...
  },
  tray = {
    open_on_start = false,
    ...
  },
  ...
})
```

When I call `require("dapui").toggle()` to hide the sidebar, the sidebar goes but the tray opens up.

This is technically correct, since the tray visibility has been toggled. But ideally, I would like to disable the tray becoming visible on _toggle_, since `open_on_start` is false.

Is this something that can be addressed in the plugin, or should users come up with a workaround for cases like these in personal configs?

**Comment by rcarriga** [comment]
This is expected behaviour and I don't think I want to change it. If you just want to toggle the sidebar you can pass "sidebar" to the `toggle`. Is that what you're looking for?

**Comment by farbodsz** [comment]
Great point - I didn't realise I could pass the sidebar as an argument here. Thanks!
