### ISSUE TITLE
Conflict with vista.vim maybe

### ISSUE THREAD

**Issue by FelipeMarcelino** [rcarriga/nvim-dap-ui#67]
When I try open nvim-dap-ui I got a message:

![image](https://user-images.githubusercontent.com/15383718/142960310-03b991e6-2e75-4da7-b625-e58f5aef2121.png)

And then after the error, vista window opens automatically. 

![image](https://user-images.githubusercontent.com/15383718/142960363-b3c03613-96d2-44fc-8e19-0ad8e79fe579.png)

**Comment by rcarriga** [comment]
The error message looks like you haven't called `setup` beforehand, have you? 

I have no clue why vista is opening, I'd need more details on how you're opening dap-ui

**Comment by FelipeMarcelino** [comment]
Yes, I have. Take a look:

![image](https://user-images.githubusercontent.com/15383718/143000996-b74e3a91-d5b1-4840-a236-9d565887bd47.png)

I am using a keybinding to open daui:

map("n", "<leader>dui", "<cmd>lua require'dapui'.toggle()<CR>", default_opts_dap)

**Comment by FelipeMarcelino** [comment]
It is working now, I create a separate file dapui.lua and put all the default configurations there and sourced it.
