### ISSUE TITLE
Evaluating does not work in visual mode

### ISSUE THREAD

**Issue by Thieso** [rcarriga/nvim-dap-ui#69]
Hello, thanks for this nice plugin. 

I have a small problem when evaluating a visual selection in python. The mapping I am using is 
```
vnoremap <leader>di :lua require("dapui").eval()<CR>
```

The problem is that with this only the first word under the cursor is evaluated. You can see this in the following picture. 

![dapui](https://user-images.githubusercontent.com/15210390/144232258-4738f028-d042-4196-8083-8f330425c35a.png)

I visually selected everything to the right of the equal sign but it only evaluates the `np`. Is this desired behavior?

**Comment by rcarriga** [comment]
No that is not the desired behaviour. The reason for the wrong selection is that you're using `:` to start the mapping which changes modes and removes the selection. Instead use `<cmd>`, for more info see `:help <cmd>`

**Comment by Thieso** [comment]
Ah yes that works. My bad, thanks for clearing that up.

**Comment by ObserverOfTime** [comment]
I get the same issue when setting the keymap from lua:
```lua
vim.keymap.set({'n', 'v'}, '<Leader>De', function()
    package.loaded.dapui.eval()
end, {silent = true})
```

**Comment by rcarriga** [comment]
@ObserverOfTime that mapping works for me. Could you update your neovim to latest and if the problem persists please open a new issue?

**Comment by ObserverOfTime** [comment]
It seems to work with `{'n', 'x'}` but not `{'n', 'v'}`. That's fine.
