### ISSUE TITLE
eval does not work as expected using jdtls

### ISSUE THREAD

**Issue by elevin72** [rcarriga/nvim-dap-ui#7]
When hovering over a variable (reference to some object), and doing ```:lua require'dapui'.eval()```, a popup window containing a single integer shows up. I can't find any sort of relationship between that integer and the actual value of the object.
![image](https://user-images.githubusercontent.com/11501767/116822519-ea9ca080-ab87-11eb-8315-f22501ede392.png)

This is really a shame becasue dap.ui.variables.hover() gives great results, but the window behavior is weird. dapui.eval() has fantastic window behaviour, but the actual results make no sense.

**Comment by elevin72** [comment]
After looking at the code a bit, it seems that hover.lua line 32 should not have the pound symbol, as shown below. Still formatting is a bit off, may do a PR.
```local val = " "..response.result.." "```

**Comment by rcarriga** [comment]
Thank you for the PR!

**Comment by elevin72** [comment]
I would like to make it so hover windows have a logical height and width, instead of always having height of 1 and length of the entire string. Just pretty bad in lua, so it may take a while. If you know how, that would be cool. 
Gotta say, I'm loving this plugin.

**Comment by rcarriga** [comment]
Thanks for the love! I've added in the multiline display of variables in the eval window, which should display values the same as the variables window. Please let me know if there's any issue with it!

**Comment by elevin72** [comment]
Thanks! I'll take a look later.

**Comment by elevin72** [comment]
It seems pretty broken to me. The popup always shows up in the top left of the screen, and the content is just the name/type of the variable with no other data in it.
![image](https://user-images.githubusercontent.com/11501767/117549573-deab5580-b043-11eb-819e-a14e43153561.png)

**Comment by rcarriga** [comment]
You're right the position is off which is odd, I will look into that but the value shown seems to be correct as it's the same as the one in the "scopes" window. What are you expecting to see instead? If you type `.scopes` into the REPL does it appear differently?

**Comment by elevin72** [comment]
I was hoping to see the actual value of the plane. In the REPL that same variable will appear, but then pressing enter on it will expand it and show me all the fields in that object. Pressing enter in the dapui hover windows has no effect.

**Comment by rcarriga** [comment]
Ah OK well that's not really the intention of the eval window, it's only meant for a quick value check. Deeper inspection is handled by the `scopes` window which should do what you want.

**Comment by elevin72** [comment]
Oh it was my understanding that it was supposed to resemble behavior of dap.ui.variables.hover().
Thanks for your help!
