### ISSUE TITLE
Panel with user text to show mappings

### ISSUE THREAD

**Issue by DavidGamba** [rcarriga/nvim-dap-ui#70]
Related to #65 but maybe easier to implement.

I have a few mappings that I use with dap that I tend to forget.
It would be great if the dap UI could include A small user text space besides the Watches, Stacks, Breakpoints and Scopes.
something like ``` user_text = `xxx` ``` allowing for multiline comments. In that space I would put a list of my custom mappings so they are easy to remember when I start a debugging session.

**Comment by rcarriga** [comment]
I think something like https://github.com/folke/which-key.nvim would better solve your problem. IMO this feature would not be useful to most people. If you wanted to, you could just create a mapping for a floating window to show your mappings alternatively.

**Comment by DavidGamba** [comment]
Thanks for getting back to me, the floating window idea is something I'll look into.
