### ISSUE TITLE
Better docs on integration with nvim-dap

### ISSUE THREAD

**Issue by DanielCardonaRojas** [rcarriga/nvim-dap-ui#71]
Hey @rcarriga  thank you for creating this awesome plugin, having dap and plugins like this is one the things that motivates me more into switching fulltime into neovim.

Reading through nvim-dap documentation I noticed I could automatically open the UI hooking into DAP's  `stopped` event
I bet this is something other folks will like to add to their configuration which I think is worth documenting.

Maybe a like snippet like this in the readme: 

```lua
      local dap = require('dap')

      dap.listeners.before['event_stopped']['rcarriga/nvim-dap-ui'] = function(session, body)
        print('Stopped at breakpoint')
        require("dapui").open()
      end

      dap.listeners.before['event_terminated']['rcarriga/nvim-dap-ui'] = function(session, body)
        require("dapui").close()
      end

```

I'm using packer and put that into the setup function.

**Comment by rcarriga** [comment]
Hey thanks for the feedback! Actually this used to be setup by default but I removed it to allow more  flexibility, never thought to document it, will do :ok_hand:
