### ISSUE TITLE
Completion in repl

### ISSUE THREAD

**Issue by meijieru** [rcarriga/nvim-dap-ui#72]
nvim-dap supports special commands like `.continue`.
Can we enable completion in the repl buffer?

**Comment by rcarriga** [comment]
The repl is the same one as nvim-dap so it should have any of the completion working the same as it would if you ran `dap.repl.open()` (which is what nvim-dap-ui is doing)

**Comment by mfussenegger** [comment]
This should work with https://github.com/mfussenegger/nvim-dap/pull/397

**Comment by rcarriga** [comment]
Closing this as it should be working and I've not heard otherwise
