### ISSUE TITLE
Feature request: query state of dap-ui

### ISSUE THREAD

**Issue by ray-x** [rcarriga/nvim-dap-ui#75]
I am integrating dap-ui with go.nvim. I am looking for a way to know if tray or sidebar is shown or not.

**Comment by rcarriga** [comment]
Hmm what's your use case for knowing if they're open or not? Right now you can do 
```lua
require("dapui.windows").sidebar:is_open()
require("dapui.windows").tray:is_open()
```
though that was not written to be used externallly.

**Comment by ray-x** [comment]
Thanks! it works for me.
