### ISSUE TITLE
Display newest outputs in tray

### ISSUE THREAD

**Issue by Nocturne-K** [rcarriga/nvim-dap-ui#76]
Now the tray displays the oldest outputs if I don't scroll down by myself, which is kind of inconvenient. Is there a way I can make it automatically scroll down to the bottom when the program generates new output?
Btw, thanks a lot for this ui.

**Comment by rcarriga** [comment]
The REPL is actually just the REPL from nvim-dap so you'll have to open an issue there as nvim-dap-ui can't control how it operates, only where it opens

**Comment by rcarriga** [comment]
Closing as this is nvim-dap related
