### ISSUE TITLE
Disable/Enable existing conditional breakpoint

### ISSUE THREAD

**Issue by Badhi** [rcarriga/nvim-dap-ui#77]
Sometimes a developer may add a conditional breakpoint which needs to be disabled and re-enabled. This can be achieved right now by completely removing the breakpoint. But re-adding it needs the condition to be given again and again. 

Is there a way to achieve this by the plugin itself?

**Comment by rcarriga** [comment]
I've added a new `toggle` mapping for the breakpoints buffer, please try the latest commit :grin:

**Comment by Badhi** [comment]
Hi! Thanks for the feature. I tried the `toggle`, but the toggling seem to take effect only if I restart the debug session. Is that the behavior you intended? 

I'd expect it to disable/enable right after I disable or enable it. 

If its unclear I'll try to show an example. Btw, I'm trying the feature for `c++`

**Comment by rcarriga** [comment]
That was due to how rendering worked. This should be working as expected now
