### ISSUE TITLE
Hover window is not cleanly closed when using mapping

### ISSUE THREAD

**Issue by przepompownia** [rcarriga/nvim-dap-ui#78]
Steps:
1. use `lua require('dapui').eval()` on a visual selection
2. jump to the float window 
3. use any mapping (e.g. the default `<ESC>`) configured to close it
4. repeat step `1.`

I get
```
E5108: Error executing lua .../pack/bundle/opt/nvim-dap-ui/lua/dapui/windows/float.lua:68: Invalid window id: 1002      
stack traceback:                                                                                                        
        [C]: in function 'nvim_set_current_win'                                                                         
        .../pack/bundle/opt/nvim-dap-ui/lua/dapui/windows/float.lua:68: in function 'jump_to'                           
        ...ctgx/.vim/pack/bundle/opt/nvim-dap-ui/lua/dapui/init.lua:60: in function 'eval'                              
        [string ":lua"]:1: in main chunk                                                                                
Press ENTER or type command to continue   
```

If window is closed with [CursorMoved](https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/windows/init.lua#L136) autocommand, then `open_float` seems to be [emptied](https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/init.lua#L81) and the error above does not occur.

**Comment by rcarriga** [comment]
The floating window should be cleared out by the mapping as well and I can't reproduce unfortunately.
The code here https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/windows/init.lua#L130-L139 applies an autocmd which should handle the window closing even in an unexpected way. 

If you're willing to debug yourself, you can see if `dapui.windows.close_float` is actually being called and if so why it's not closing the window. 

If not I'll need a more concrete reproduction with a minimal init.vim/init.lua unfortunately.

**Comment by przepompownia** [comment]
In https://github.com/przepompownia/dap-ui-test please run `make test-close-hover-window`. 

Note that `lua require('dapui.windows').close_float('DAP Hover')` is not executed after `nvim_win_close()`.

**Comment by rcarriga** [comment]
Once again thanks for the excellent reproduction! I found the issue :grin: Please try with the latest commit, the floating window should always be handled approopriately

**Comment by przepompownia** [comment]
Thank you too! At the moment I see that on the test environment the change works without errors and I can assume that we can close this issue.
