### ISSUE TITLE
Scratch buffers are left after hover evaluation.

### ISSUE THREAD

**Issue by przepompownia** [rcarriga/nvim-dap-ui#81]
In https://github.com/przepompownia/dap-ui-test please run `make test-close-hover-window` then close, select and evaluate the same expression again (`gv`, `,de`) more than one time. With `ls!` observe new scratch buffers. 

![image](https://user-images.githubusercontent.com/11404453/153848450-7fa66a2b-11b5-47da-96a5-e685c76c3fda.png)

On the screenshot we can see the buffer 4 (`:sb 4`). 

I was hoping that the [72f6020](https://github.com/rcarriga/nvim-dap-ui/commit/72f6020b66a4ea2bbc929931514b7c47206dde55) can resolve it so I deferred creation of this issue.

**Comment by rcarriga** [comment]
Should be fixed in latest commit!

**Comment by przepompownia** [comment]
I see no orphan buffers on the test environment, thanks!
