### ISSUE TITLE
Problem with rendering large content

### ISSUE THREAD

**Issue by przepompownia** [rcarriga/nvim-dap-ui#82]
As I mentioned in https://github.com/rcarriga/nvim-dap-ui/issues/80#issuecomment-1042188487 I have problems with rendering large content in evaluation float windows. In https://github.com/przepompownia/dap-ui-test I created an example (see `make large-hover-content`) to show it.

```
Error executing vim.schedule lua callback: ...t/pack/bundle/opt/nvim-dap-ui/lua/dapui/render/state.lua:139: Vim:E322: line number out of range: 1 past the end
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        ...t/pack/bundle/opt/nvim-dap-ui/lua/dapui/render/state.lua:139: in function 'render_buffer'
        ...st/pack/bundle/opt/nvim-dap-ui/lua/dapui/render/loop.lua:99: in function 'run'
        ...p-ui-test/pack/bundle/opt/nvim-dap-ui/lua/dapui/init.lua:131: in function 'receiver'
        ...-ui-test/pack/bundle/opt/nvim-dap-ui/lua/dapui/state.lua:158: in function '_emit_refreshed'
        ...-ui-test/pack/bundle/opt/nvim-dap-ui/lua/dapui/state.lua:79: in function 'c'
        ...dap-ui-test/pack/bundle/opt/nvim-dap/lua/dap/session.lua:579: in function <...dap-ui-test/pack/bundle/opt/nvim-dap/lua/dap/session.lua:573> 
```

In my real environment effects are worse but I hope that this example can help you fix the bug. Otherwise I can make further investigation how to reproduce it.

**Comment by rcarriga** [comment]
Hmm I don't seem to be getting the same issue. I'll note that the hover window didn't open for me with your example, but I opened a hover on the `largeArray` variable and saw no issue. This could be because of either my or your plugins changing the example.

> In effect, the debugger log file get the size that exhaust the free space on a filesystem and nvim needs to kill with -9. I need some free time to prepare some reproduction.

If you're able to grab some of that log it might be useful in figuring out why there's an issue as it sounds like there's a loop in the variable chain

**Comment by przepompownia** [comment]
At the moment I upgraded the test to show what happens with no user interaction. 

On the screencast I commented out hovering by script and run it manually to show the moment of sending requests.

https://user-images.githubusercontent.com/11404453/154806737-f6f76b97-85c1-4015-961c-c8e11f9920f1.mp4

**Comment by przepompownia** [comment]
I noticed that the evaluating an empty `stdClass` object can show this behaviour too.

**Comment by rcarriga** [comment]
Thanks for getting reproduction working. The root issue was a recursive call (as expected) due to allowing a "repl" context which wasn't anticipated before. This should now be working in the latest commit :grin:

**Comment by przepompownia** [comment]
Thanks @rcarriga! No explosion observed in the test environment - both on tiny and large objects!
