### ISSUE TITLE
Need to `close()` at `WinClose` on the code window

### ISSUE THREAD

**Issue by przepompownia** [rcarriga/nvim-dap-ui#85]
Hi, 

similarly to some previous issue there is no cleaning the internal state when the tab containing dap-ui is closed manually, e.g. by `tabclose`.

For example, consider the code that places UI in a separate tab:
```lua
local debugWinId = nil
local api = vim.api
local function openTabForThread(threadId)
  if nil ~= debugWinId and api.nvim_win_is_valid(debugWinId) then
    api.nvim_set_current_win(debugWinId)
    return
  end

  vim.cmd('tabedit %')
  debugWinId = vim.fn.win_getid()
  vim.cmd('autocmd WinClosed ' .. debugWinId .. ' ++once lua require"dapui".close()')
  require('dapui').open()
end

dap.listeners.before['event_stopped']['arctgx-dap-tab'] = function(session, body)
  openTabForThread(nil)
end

dap.listeners.after['event_thread']['arctgx-dap-tab'] = function(session, body)
  if body.reason == 'started' then
    openTabForThread(body.threadId)
  end
end
```
An autocommand similar to `vim.cmd('autocmd WinClosed ' .. debugWinId .. ' ++once lua require"dapui".close()')` should be IMHO a part of nvim-dap-ui and not needed there.

**Comment by rcarriga** [comment]
Thanks for the report! I've gone a different route, because the tray and sidebar can be closed separately. You should now see that either section being closed without using `dapui.close` will still be detected and toggle works as expected

**Comment by przepompownia** [comment]
It works and is probably faster than using vim autocommands. Thank you too.
