### ISSUE TITLE
More than one sidebar?

### ISSUE THREAD

**Issue by riddlew** [rcarriga/nvim-dap-ui#86]
After installing dap-ui and looking at the sample config, seems that there is only one sidebar. Is it / would it be possible to have more than one sidebar? What I have in mind is I'd like to have two sidebars, one has scopes and watches, the other has breakpoints and frames. This would allow me to give each section more vertical screen space instead of having to scroll constantly. This would allow me to place them wherever I want instead of grouping them together, such as one sidebar on the left, one on the right, and the repl and code in the middle.

**Comment by rcarriga** [comment]
I haven't updated on this so just wanted to give the state of things. This is actually very easy from the perspective of nvim-dap-ui internals and I do have it working just fine. However when it comes to opening and closing it's a bit more complex. Neovims window opening is a bit of a pain to use and the way it works in dap-ui right now is a bit hacky (https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/init.lua#L181) so I just need to refactor the code to find a nice way to make sure all the layouts have the size that is desired by the user

**Comment by rcarriga** [comment]
OK have this implemented in #105 if you want to try it out. Will merge after a little more testing
