### ISSUE TITLE
Does this work for javascript? (node)

### ISSUE THREAD

**Issue by NullVoxPopuli** [rcarriga/nvim-dap-ui#87]
VSCode has a "Javascript debug terminal", which is really nice, because you can place a breakpoint on any file and vscode attaches itself to every thread/process/worker that's spawned so breakpoints don't get skipped. 

Can nvim-dap-ui do this? 
if so? how?

**Comment by rcarriga** [comment]
This is an issue for nvim-dap unless I'm misunderstanding. There have been mixed results in getting javascript working. You can see some of the progress here https://github.com/mfussenegger/nvim-dap/issues/136#issuecomment-906149404
