### ISSUE TITLE
Add intergrated terminal element

### ISSUE THREAD

**Issue by rekaerst** [rcarriga/nvim-dap-ui#88]
By default, nvim-dap opens a large integrated terminal window below the main window.  It would be nice if nvim-dap-ui could manage this window and put it at the bottom tray.

e.g.
- default:
![image](https://user-images.githubusercontent.com/52642831/158074557-0f0455b2-c308-4e8e-95f9-85933976fe14.png)
- ideal:
![image](https://user-images.githubusercontent.com/52642831/158074423-e0f622a4-0992-40e1-8375-c50792925855.png)

**Comment by igorlfs** [comment]
> On that same note @rcarriga is there a way to at least make dapui clean the additional window when you call dapui.close ? Since it stays open after the tray and sidebars are closed.

You can use an autocommand to close the terminal when the exit code is 0, i.e.
```{vimscript}
autocmd TermClose * if !v:event.status | exe 'bdelete! '..expand('<abuf>') | endif
```

**Comment by rcarriga** [comment]
OK I've added a new `console` element in #104 :grin:
