### ISSUE TITLE
DAP Stacks not getting updated when you step into function

### ISSUE THREAD

**Issue by furkanbiten** [rcarriga/nvim-dap-ui#91]
Hi, 
Great plugin! 

When I step into some function with nvim.dap, it seems that DAP Stacks sidebar is not updated from nvim-dap-ui side. From nvim.dap side, all the frames are shown properly.

**Comment by rcarriga** [comment]
I'm not seeing any issue myself, can you put together a sample file to reproduce?

**Comment by rcarriga** [comment]
Hit the wrong button :man_facepalming:

**Comment by furkanbiten** [comment]
Is it ok if I record the screen? Or do you need something else specifically?

**Comment by rcarriga** [comment]
A screen recording would be good to know what's happening but to find the cause I'll need to know what DAP adapter and config you're using and a simple file to debug. I need to be able to run it locally myself.

**Comment by furkanbiten** [comment]
Here is a short video showing the problem:
https://user-images.githubusercontent.com/22663927/159715508-775a8b5d-6fc8-49c4-96a6-d6cb519364fa.mp4
I am trying to debug in python with debugpy with configuration:
 ` EOF
 16 lua << EOF
 17     local dap = require('dap')
 18     dap.adapters.python = {
 19       type = 'executable';
 20       command = '/home/abiten/miniconda3/envs/transformers/bin/python';
 21       args = { '-m', 'debugpy.adapter' };
 22       justMyCode=false;
 23     }
 24 EOF
 25 lua << EOF
 26     require('dap')
 27     vim.fn.sign_define('DapBreakpoint', {text='🛑', texthl='', linehl='', numhl=''})
 28     local dap = require('dap')
 29     dap.configurations.python = {
 30       {
 31         type = 'python';
 32         request = 'launch';
 33         name = "Launch file";
 34         program = "${file}";
 35         justMyCode=false; 
 36         args = function()
 37         ¦   local args_string = vim.fn.input('Arguments: ')
 38         ¦   return vim.split(args_string, " +")
 39         end;
 40         pythonPath = '/home/abiten/miniconda3/envs/transformers/bin/python';
 41       },
 42     }
 43 EOF
`
I will try to find a simpler code to showcase the problem as well.

**Comment by furkanbiten** [comment]
ooof sorry for the shit formatting!

**Comment by furkanbiten** [comment]
`
import numpy as np

def my_func(a,b):
    return a.dot(b)

if __name__ == "__main__":
    a = np.zeros(10)
    b = np.ones(10)
    my_func(a,b)
`
In this simple python code, if you put a breakpoint at `b=np.ones(10)` and then run step_into, then nvim-dap shows all the frames but nvim-dap-ui only shows <module> simple.py: 8.

**Comment by rcarriga** [comment]
Ah I see what's happening. So a stack frame can be marked as `subtle` which nvim-dap-ui will not display (this is what VSCode does AFAIK). Debugpy will mark frames from external libraries as subtle. I could add a mapping to toggle these frames as I can definitely see the use in inspecting them

**Comment by furkanbiten** [comment]
Much appreciated!

**Comment by rcarriga** [comment]
OK you can now toggle subtle frames, please try the latest commit :smile:

**Comment by furkanbiten** [comment]
Awesome it works! You can toggle into the code with key `t` in the Dap Stacks window. 

Thank you my good sir 😄
