### ISSUE TITLE
Multiple running instances?

### ISSUE THREAD

**Issue by ravenxrz** [rcarriga/nvim-dap-ui#93]
I use dap to debug cpp.

If I start a debug session, the 'DAP Stacks' area is correct, then I terminate it by `:lua require('dap').terminate()`:

![image](https://user-images.githubusercontent.com/44746032/162360256-45d514c9-2df3-43a8-b075-e612d45d42e4.png)

and restart a new debug session, the 'DAP Stacks' area shows two test instances.

![image](https://user-images.githubusercontent.com/44746032/162360338-19ee86f4-69fd-4959-ab4c-c01156b38b7e.png)

An interesting thing is If I terminate the process by Ctrl+c in the terminal window, everything works fine.

**Comment by rcarriga** [comment]
Could you check with latest commit please?

**Comment by ravenxrz** [comment]
> Could you check with latest commit please?

Everything works fine now :)
