### ISSUE TITLE
[Question] Hide types in watch/eval view

### ISSUE THREAD

**Issue by igorlfs** [rcarriga/nvim-dap-ui#95]
Is there a way to hide variable types in the watch window and when evaluating expressions? At least with C++ (lldb-vscode) it gets really clunky really fast, eg

![image](https://user-images.githubusercontent.com/84649544/162635161-f4741eb7-b95a-49d5-ae8c-691b594ca9f1.png)

**Comment by rcarriga** [comment]
I've added a config option to limit the type length, and you can set it to zero to completely disable types

**Comment by igorlfs** [comment]
Thank you! Setting max_type_length as 0 works as intended. However, without the type highlight, the render feels bleak, as both the variables and their values are the same color. Nvim-dap's widgets api works around this by highlighting variables, eg:
![image](https://user-images.githubusercontent.com/84649544/163714550-eaeaa532-ee54-454d-ac0d-fa1295229901.png)
vs dap-ui without types:
![image](https://user-images.githubusercontent.com/84649544/163714628-24b5acd5-24af-413e-9c82-d3d2a2b45bc7.png)
Do you think it's adequate to have a similar feature with dap-ui? If you think it deservers it's own issue, feel free to close this one.

**Comment by rcarriga** [comment]
You can redefine the highlights as you want. The one for variable names is `DapUIVariable` :smile:  They're defined here https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/config/highlights.lua

**Comment by igorlfs** [comment]
Thank you! Closing!
