### ISSUE TITLE
Override showing unneeded sign columns

### ISSUE THREAD

**Issue by przepompownia** [rcarriga/nvim-dap-ui#96]
![image](https://user-images.githubusercontent.com/11404453/164571170-1f7125d8-9608-48b3-8793-89831c05740a.png)

In https://github.com/przepompownia/dap-ui-test (see `make long-line-hover`) I put `set signcolumn=auto:1-9` to demonstrate showing unneeded signcolumns. 

Probably each dap-ui window should have `signcolumn` set to `auto` to override initial setting.

**Comment by rcarriga** [comment]
Ah good point! Fixed in latest commit

**Comment by przepompownia** [comment]
Thanks!
