### ISSUE TITLE
Autocomplete in REPL

### ISSUE THREAD

**Issue by megawubs** [rcarriga/nvim-dap-ui#98]
This is a feature request. I don't know if it's possible or not, but I would like to be able to have LSP powered autocomplete in the REPL window. 

Is this something that can be configured manually or does this plugin have to implement/use it?

**Comment by rcarriga** [comment]
So I don't think that LSP could be used as it uses the cursor position in a file to determine completion candidates. However there is built-in omnifunc for the REPL and other buffers. I also just threw together this https://github.com/rcarriga/cmp-dap for an nvim-cmp source :smile: Depending on the server it should be pretty good for completion as it can read the scope at run time.

**Comment by megawubs** [comment]
This looks awesome. Will play with it later today

**Comment by bageljrkhanofemus** [comment]
```lua
vim.api.nvim_create_autocmd({ "Filetype" }, {
	pattern = "dap-repl",
	callback = function()
		require("dap.ext.autocompl").attach()
	end,
})
```
Is another option

**Comment by rcarriga** [comment]
I'm going to close this as I don't believe there's an easy way to integrate LSP completion and there is already built-in omnicfunc provided by nvim-dap and now the nvim-cmp source for DAP provided completions
