### ISSUE TITLE
Error with setting column for extmark

### ISSUE THREAD

**Issue by przepompownia** [rcarriga/nvim-dap-ui#99]
While I did not reproduce this error on my test environment please see at the screenshots below. At the first glance it looks like acting on outdated extmark data. Note `end_col = 129` from existing extmark and actual number of columns (~38) in line 15 of the stacks buffer. In this example it occurs on the second jump to the same breakpoint (with different stack). 

![image](https://user-images.githubusercontent.com/11404453/165848315-6ca01f02-bd20-411e-b03b-ac76cc352bcf.png)
![image](https://user-images.githubusercontent.com/11404453/165848485-ad09fe9f-f51a-4bfb-85c3-9bd1be84fd83.png)
![image](https://user-images.githubusercontent.com/11404453/165849573-12dad8ad-4c04-4fc9-afa8-b67fb1baa92b.png)
(I put screenshots instead of code block because of some problems with my desktop env. at the moment)

**Comment by przepompownia** [comment]
I guess (but not sure) that it occurs when `content_width` is less than `details.end_col`. 
```diff
diff --git a/lua/dapui/render/line_hover.lua b/lua/dapui/render/line_hover.lua
index 3be97a9..f0679a3 100644
--- a/lua/dapui/render/line_hover.lua
+++ b/lua/dapui/render/line_hover.lua
@@ -97,7 +97,7 @@ function M.show()
     local _, _, col, details = unpack(mark)
     if not details.end_col or details.end_col > orig_col then
       details.end_row = 0
-      details.end_col = details.end_col and (details.end_col - orig_col)
+      details.end_col = details.end_col and math.min(details.end_col - orig_col, content_width)
       col = math.max(col, orig_col)
       api.nvim_buf_set_extmark(hover_buf, namespace, 0, col - orig_col, details)
     end
```
The above patch seems to fix the bug but it is probably only a workaround. I did not found what is the source of too big `end_col`.

**Comment by rcarriga** [comment]
Yeah the end_col should always be <= the content width so this solution would just be a workaround. I'll add error handling just so it doesn't raise an error for users while I investigate

**Comment by przepompownia** [comment]
`pcall` from [3eec525](https://github.com/rcarriga/nvim-dap-ui/commit/3eec5258c620e2b7b688676be8fb2e9a8ae436b2) also works :+1:
